### ISSUE TITLE
Teleporting glitch is still a thing

### ISSUE THREAD

**Issue by Tander9** [vret001/KU#10]
Basically every dash type attack that moves you forward can teleport you back to where you used that move. This will result in damage being dealt to you and although it doesn't happen as consistently as before, it's still an issue. Also MG21's "Dash" and Jet Jaguar Beta's "Wandering Destruction" move towards the ground.

I experienced the teleportation damaging glitch with MG21 at: 10:59 PM PST 2/17/2022

Edit: G21's "Duel Bash" does not get effected by this glitch, so there may be some exceptions.

**Comment by vret001** [comment]
Part of #32, please followup there.
