### ISSUE TITLE
The main title is glitched

### ISSUE THREAD

**Issue by SilveFox64** [vret001/KU#100]
**Describe the bug**
The problem is the next: the charge tittle is always sending the same message, and i cant play, i send the photo.

**When did you last experience the issue:**
Yesterday, 23/02/2022 on the night

**To Reproduce**
See error

**Expected behavior**
I dont know.

**Screenshots**
![20220224_164327](https://user-images.githubusercontent.com/100384585/155620281-aa4917c4-e47d-4d30-af25-2b57c5eb7547.jpg)

**Desktop (please complete the following information):**
 - OS: [windows 7]
 - Browser [Fire Fox]
 - Version [Unknow]

**Smartphone (please complete the following information):**
 I dont have

**Additional context**
Nothing else, i just wanna play my favorite game, please.

**Comment by Opalara** [comment]
yeah i cant participate in the 1.5x exp event because of this. i uninstalled and reinstalled roblox twice to see if that would work, and nothing. its definintely a KU problem as i dont have this kinda problem in any other game.

**Comment by SilveFox64** [comment]
Hes right, we need a quick solution because im grinding my gigan, please

**Comment by vret001** [comment]
This should be fixed in the latest update.
