### ISSUE TITLE
Can’t load into ku

### ISSUE THREAD

**Issue by Lazuh** [vret001/KU#108]
**Describe the bug**
I wanted to load into ku but it said that “roblox datastore may be down” and I don’t know what to do I need help

**When did you last experience the issue:**
The last time it happened was on a wednesday and the issue has been going on for the past 3 days 

**To Reproduce**
See error

**Expected behavior**
I don’t know

**Screenshots**
screenshot link~
![](https://i2.paste.pics/b505c16a2805b173135ed3c395365125.png)

**Smartphone (please complete the following information):**
 - Device: Ipad 8th Generation 
 - OS: 15.3.1 
 - Browser Safari
 - Version 15

**Comment by QxlDark** [comment]
same for me, this gotta be fixed asap!

**Comment by vret001** [comment]
Hi, can you press f9 and provide a screenshot of the logs? Thank you.

**Comment by Lazuh** [comment]
> Hi, can you press f9 and provide a screenshot of the logs? Thank you.

I’m on mobile so I don’t know if I can do that or not

**Comment by vret001** [comment]
> > Hi, can you press f9 and provide a screenshot of the logs? Thank you.
> 
> I’m on mobile so I don’t know if I can do that or not

You can type /console in the chat

**Comment by Lazuh** [comment]
> > > Hi, can you press f9 and provide a screenshot of the logs? Thank you.
> > 
> > 
> > I’m on mobile so I don’t know if I can do that or not
> 
> You can type /console in the chat

okay

**Comment by Lazuh** [comment]
> Hi, can you press f9 and provide a screenshot of the logs? Thank you.

hey, i got the screenshot of the logs 
![](https://i2.paste.pics/5865695715d957e7c573204eb56d5ab1.png)

**Comment by QxlDark** [comment]
[image: Screen Shot 2022-02-25 at 10.35.14 PM.png]

**Comment by vret001** [comment]
This should be fixed in the latest update.

**Comment by Meccarex** [comment]
![RobloxScreenShot20220225_220018424](https://user-images.githubusercontent.com/100460230/155832141-b9afb8f7-a69c-4eeb-964f-46acc6c7f3e0.png)
 For some reason I can't join the game. it been like this for 4 days

**Comment by Meccarex** [comment]
nvm
![RobloxScreenShot20220226_070253645](https://user-images.githubusercontent.com/100460230/155847935-895ddeca-3a1e-4bae-a736-641fe98152de.png)
