### ISSUE TITLE
Titanus Mosura's "Royal Flash" attack is glitched.

### ISSUE THREAD

**Issue by Xeadon** [vret001/KU#11]
It now sends your straight down but before used to send you a diagonal forward 

2/17/22
1:31 EST

Use the 4th Attack; Royal Flash.

It should send me a forward direction rather then straight down.

https://user-images.githubusercontent.com/99947920/154630282-7f4764c7-3a3d-4502-b849-bd9381ddcf2a.MOV

**Comment by vret001** [comment]
This should be fixed.
