### ISSUE TITLE
G14 R roar is still broken

### ISSUE THREAD

**Issue by ZaddyDaddy** [vret001/KU#112]
**Describe the bug**
For G14’s Legend’s roar, when you press it, the animation is sped up which makes the roar last longer than the animation
**When did you last experience the issue:**
A date and time
Yesterday when I was using g14
**To Reproduce**
1. Use G14
2. Click on Legend’s Roar

**Expected behavior**
What I expected to happen is for the roar to finally be fixed, but no
**Screenshots**
Ah yes, a screenshot of a moving animation

**Comment by vret001** [comment]
Duplicate of #53
