### ISSUE TITLE
Mecha Godzilla 2021 dashing: the dashing on MG21s isn't working well sometimes when I dash it teleports me back to my original location and I also lose health from it. Another problem is roaring, when I roar it seems to have a big cool down and it also takes away my charge percent.

### ISSUE THREAD

**Issue by KaijuEnthusiast** [vret001/KU#117]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Please fill out the format correctly
