### ISSUE TITLE
control lock dosen't work

### ISSUE THREAD

**Issue by TheManBehindEverything** [vret001/KU#118]
When I turn the control lock dosent follow
![image_2022-02-26_100627](https://user-images.githubusercontent.com/100480040/155848044-8a2e81f7-a5b2-4707-a14c-bd7784afd9f4.png)

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![RobloxScreenShot20220226_100131067](https://user-images.githubusercontent.com/100480040/155848291-76a92c89-2915-4603-ae6e-e11dc2314996.png)

**Comment by vret001** [comment]
Please follow the format before posting.
