### ISSUE TITLE
Kyrius missiles make it lose health

### ISSUE THREAD

**Issue by FireRaptor999** [vret001/KU#12]
The bug i found is whenever I try to use kyriu type 2s missiles I lose health, and I lose health if they explode near me
 You just get on kyriu type 2 and use missiles

I expected to be able to use missiles without damaging myself 
 1:24 pm cst 

I encountered the error on xbox

(Dunno if you still need to know but I'm submitting on Samsung galaxy s9 on crome)

**Comment by FireRaptor999** [comment]
The bug seems to happen randomly sometimes

**Comment by vret001** [comment]
Hi, is this still happening?

**Comment by vret001** [comment]
Do you teleport, as the dash ends, or after moving after the dash?

**Comment by vret001** [comment]
Part of #32, please followup there.
