### ISSUE TITLE
Some kaijus with no animation

### ISSUE THREAD

**Issue by Utensil386** [vret001/KU#123]
**Describe the bug**
the bug just makes lots of the kaiju's t pose
**When did you last experience the issue:**
A date and time
2022 Feb. 26
**To Reproduce**
1. Go to '...'happens naturally

**Expected behavior**
just kaijus tposing with no animation
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]windows
 - Browser [e.g. chrome, safari]Chrome
 - Version [e.g. 22]10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Hi, this is simply the nature of how animations work on Roblox, they can take a little while to download.
