### ISSUE TITLE
Pulses are very choppy instead of being smooth

### ISSUE THREAD

**Issue by VerretsMinion** [vret001/KU#126]
Username:loltafli(VerretsMinion

Issue time and date: after framework update
Server age:  happens on every server

Issue description: Pulses doesnt seem to be working properly now.Pulses extend very slow and kinda lags while expanding (not the game) here is a video for the bug

Steps to reproduce issue:
 
Videos, pictures:

https://user-images.githubusercontent.com/100492677/155859434-d42cbfdb-d7a2-4cb3-b5a7-01b997dae5aa.mp4

**Comment by todynho0n** [comment]
i hope they fix this, i get kind of agonized to see the wrists shake
