### ISSUE TITLE
Voodon's Mach Rampage attack in the air propels you upwards instead of the direction you are facing.

### ISSUE THREAD

**Issue by SansTheSkeletonMan33** [vret001/KU#13]
**Describe the bug**
When Voodon uses Mach Rampage in the air, it sends him way high up vertically instead of going in the intended direction the player is facing horizontally

**When did you last experience the issue:**
February 18th, 2022 @2:09 AM EST

**To Reproduce**
Select Voodon and Juju
Fly in the air and use Mach Rampage attack

**Expected behavior**
When the steps are followed, Voodon should propel straight upwards at a very fast speed

**Additional context**
This was happening for a while and it is yet to be noticed. Also I love using Voodon since it has a good design.

https://user-images.githubusercontent.com/99950209/154637516-2e4d41f9-633c-49d6-b29d-e1553099c79e.mp4

**Edit**
Voodon's Mach Rampage also slumps him into the ground when it is not used in the air. 

https://user-images.githubusercontent.com/99950209/154638396-aaddfefb-e3c1-4e93-bfa6-9aa8ba7a8305.mp4

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #33
