### ISSUE TITLE
Control lock moving the player in the left or right direction

### ISSUE THREAD

**Issue by AkhuRott** [vret001/KU#132]
**Describe the bug**
When ever i look left or right while using control lock then the game pushes the player in that direction

**When did you last experience the issue:**
Feb,28 2022 1:00 am 

Taiwan time

**To Reproduce**
1. enter a server and pick a kaiju
2. use control lock and look left or right
3. and then u should start going in that direction 
4. the end 

**Expected behavior**
i expected my kaiju to look in that direction,
by look i mean move its entire body to that direction

**Additional context**

https://www.awesomescreenshot.com/video/7622405?key=c79dd6a57189436ac3bc996a9c30f311

**Comment by vret001** [comment]
This should be fixed.
