### ISSUE TITLE
*Bug* 

### ISSUE THREAD

**Issue by WhKipthan** [vret001/KU#138]
*bug*
When I go out to sea with G millenium it takes my life from 400 to 400 and it is very annoying to wait to recover, I hope it will be solved soon

*Affected Kaiju*
Millenium Gojira

*version*
Update 5.4.1 

*Hour*
10:30 a. m. mexican time

*device*
PC

**Comment by vret001** [comment]
Please put all anti cheat related issues in #144

**Comment by WhKipthan** [comment]
https://user-images.githubusercontent.com/100605423/156273285-05e13052-9076-4f1b-a0ae-58c3c4ef5bbd.mp4

Evidences
