### ISSUE TITLE
Shin godzilla form 4 and heisei godzilla level problem

### ISSUE THREAD

**Issue by Ballvid** [vret001/KU#139]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ballvid** [comment]
![Screenshot 2022-02-28 105821](https://user-images.githubusercontent.com/100613309/156034077-aab21510-3e72-43d4-8701-fa989c8351cd.png)

**Comment by vret001** [comment]
Thank you for your bug report though the behavior you described is intentional. Kaijus only transfer 75 levels to a remodel.
