### ISSUE TITLE
Kumonga strange glitches

### ISSUE THREAD

**Issue by Berzerkinblaze** [vret001/KU#14]
**Describe the bug**
Kumonga takes damage when performing Arachnidian Assault while standing still.
While fighting a Kong, I got dropped below the world.

**When did you last experience the issue:**
2/18/22, 2:37:07 AM Eastern
2/18/22, 2:44:38 AM Eastern

**To Reproduce**
Stand still when using Kumonga and use Arachnidian Assault, and there's a chance you'll take damage
I've got nothing on how I dropped below the world into limbo.

**Expected behavior**
I was expecting to watch the attack play out normally and view the animation.
I was expecting to fight (and beat) the Kong.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/99952389/154642836-8a78518f-f9b9-445b-8232-5902484c8ba4.png)
https://streamable.com/aguek0
https://streamable.com/edi58e

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Mozilla Firefox
 - Version: 10

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by vret001** [comment]
Part of #32, please followup there.
