### ISSUE TITLE
Monster Zero's Idle is broken for a month

### ISSUE THREAD

**Issue by TacoStego** [vret001/KU#140]
**Describe the bug**
MZ will just T-pose instead of doing his idle animations. Same also applies in the air. This has been going on for me for about a month now. around the time titanus rodan was added.
**When did you last experience the issue:**
2/28/2022 1:45PM

**To Reproduce**
1. Go to the kaiju menu.
2. Click on MZ.
3. Wait for the character to fully load.

**Expected behavior**
For MZ to play his idle animations and not stance up in a T-pose to try and intimidate me.

**Screenshots**
https://gyazo.com/791a6dd4153825177d909c8cf7ff61c6
![eb217ebedd61fed890a8a0d3f44cd750](https://user-images.githubusercontent.com/100617454/156043556-e4ea4b62-ae52-429d-91bf-398c3a77829f.jpg)

**Desktop (please complete the following information):**
 -PC Skytech Archangel. (Kinda old but works well.) Google chrome.

**Comment by vret001** [comment]
Hi, this happens when Roblox doesn't load the animation, Unfortunately there isn't much we can do.
