### ISSUE TITLE
Anticheat false positives megathread

### ISSUE THREAD

**Issue by vret001** [vret001/KU#144]
Anticheat false positives are whenever
- You are travelling too quickly: This will teleport you backwards and damage you
- You are flying (too high off the ground as a non-flying kaiju
- A number of other, private checks

If you encounter these, please post a video here so I can identify the issue and fix it.

**Comment by vret001** [comment]
Please leave comments here with videos, etc of the anti-cheat having isuses.

**Comment by Zeely-Weely** [comment]
#207

**Comment by dragonelk** [comment]
My kajus stuck facing one direction won’t turn left or right at all
