### ISSUE TITLE
Destroyah bug

### ISSUE THREAD

**Issue by DyinL2** [vret001/KU#15]
**Describe the bug**
A clear and concise description of what the bug is. losing 1k  hp on dest for no reason while flying

**When did you last experience the issue:**
A date and time 2022/18/2

**To Reproduce**
1. Go to '...'get your dest
2. Click on '....' fly next to a player
3. Scroll down to '....'you lose 1k hp and get thrown in the water
4. See error i cant fly in the water

**Expected behavior**

**Screenshots**
i cant 
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
fix it please i cant play as destroyah without losing 1k hp each second

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #32
