### ISSUE TITLE
Wobbling Animations

### ISSUE THREAD

**Issue by Xeadon** [vret001/KU#152]
Whenever certain Kaijus do animations; walking, attacks, and dancing. They wobble and looks un anchored from the ground.

**Date and time**
The date I'm reporting this; 3/2/22. All day every day.

**Steps to Reproduce**
-Spawn in as your kaiju. 

-It cannot be your own Kaiju it has to be someone elses (you cannot see your own animations wobble) 

-Look at Kaiju with said glitch (MZ, Shin Godzilla, G14) 

**Expected behavior**
I expect it to walk the way it's supposed to walk. Anchored and stable instead of wobbling uncontrollably 

**Screenshots**
https://user-images.githubusercontent.com/99947920/156400669-e48a9e0b-fbb9-44da-86b0-88ed4ffd997d.MOV

**Console**
Model: Xbox Series X
 

**Additional context**
It's been going on for a month now and it's very un immersive and distracting; makes the game look bad.

**Comment by vret001** [comment]
I believe this is a Roblox replication issue, as this doesn't happen on other's screens and seems to be exclusive to xbox?

**Comment by VixenSaid** [comment]
This happens on mobile too.
