### ISSUE TITLE
You take damage when you spawn in for no reason.

### ISSUE THREAD

**Issue by GentleTitan** [vret001/KU#157]
**Describe the bug**
Sometimes when you spawn in quarter of your health is taken.

**When did you last experience the issue:**
03/03/2022

**To Reproduce**
1. Pick any kaiju.
2. Click spawn in any area
3. You take damage for no reason

**Expected behavior**
You shouldn't take any damage.

**Comment by vret001** [comment]
This is an anticheat issue, please leave a comment on #144
