### ISSUE TITLE
MG21 Dash Teleporting Me BackWards

### ISSUE THREAD

**Issue by AkhuRott** [vret001/KU#159]
**Describe the bug**
everytime i use the mg21 dash then the game teleports me backwards

**When did you last experience the issue:**
18:49 PM
TW time
**To Reproduce**
1. equip/use mg21
2. spawn where ever u want to
3. use the dash for mg21 "v" while holding W or forwards
4. and if u keep doing it u should teleport back wards

**Expected behavior**
i expected mg21 to dash forward 
and then i could continue doing what ever i was doing

video i recorded to show u this bug:

https://www.awesomescreenshot.com/video/7696605?key=8c44b3951c1ce899ebe2d271e396c861

**Comment by vret001** [comment]
Please put all anti cheat related issues in #144
