### ISSUE TITLE
MechaGodzilla 2021 dash bug

### ISSUE THREAD

**Issue by MemeDuud** [vret001/KU#16]
**Describe the bug**
When i dash, my character goes down instead of forward, sometimes teleports me back and damages me.

**When did you last experience the issue:**
Idk the american or something dates, ain't from here, but i experienced it on 02.18.2022

**To Reproduce**
1. Go to any place
2. Click on V (dash)
3. See error

**Expected behavior**
I expected it to work as it did before this update.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version 10

**Additional context**
nothin here

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #32
