### ISSUE TITLE
MG21 and HRodan's attack/roar names being unnecessarily changed in the framework update.

### ISSUE THREAD

**Issue by MasterMaddox64** [vret001/KU#164]
**Describe the bug**
I'm not sure if this is a bug or not but It should be fixed/changed. It bugs me a lot as the original names were so much better for these attacks/roars.
**When did you last experience the issue:**
A date and time
Anytime you be Heisei Rodan or MG21
**To Reproduce**
Be Heisei Rodan or MG21

**Screenshots**
![Attackname](https://user-images.githubusercontent.com/100883016/156671140-709109bf-21a5-48f3-b380-0fa2e6817e0e.png)
![KUAttackname](https://user-images.githubusercontent.com/100883016/156671144-c5702254-a17d-4e11-9264-fefa1dbcb356.png)

**The original attack names were: "Resound Revenge" and "Mach Assault", they describe the attacks and roars better and just sound better in **general.**

**Comment by vret001** [comment]
This was done intentionally, as such it is not a bug. You can post a suggestion to rename it.
