### ISSUE TITLE
a problem with dashes

### ISSUE THREAD

**Issue by nizankoku** [vret001/KU#165]
**Describe the bug**
when you dash any kaiju with a long dash attack like female muto, mg21, trodan, etc it teleports you back to where you started the dash/attack and that's really annoying

**When did you last experience the issue:**
many times and now minutes ago

**To Reproduce**
1. 'choose the following kaijus. female muto, mg21, trodan, jet jaguar beta, and any other kaiju with dash attack'
2. 'run the dash attack until the bug appears, it doesn't always appear'

**Expected behavior**
you will teleport back after using dash attack

**Screenshots**
this looks better in videos or try it yourself

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [opera gx]
 - Version [84.0.4316.30]

**Additional context**
the bug is not very common but if it happens to you in the middle of a fight it bothers you a lot

**Comment by vret001** [comment]
Please put all anti cheat related issues in #144
