### ISSUE TITLE
Showa gojira glitch

### ISSUE THREAD

**Issue by Showagojiraglitch19865** [vret001/KU#167]
If hitting another kaiju you will teleport the distance you travelled to hit them behind them

Use dorsal plate charge at a curtain distance or angle and you teleport

**Comment by vret001** [comment]
We are unable to reproduce the issue, if you could please follow the format as well as provide a video?

**Comment by vret001** [comment]
We are unable to reproduce the issue, if you could please follow the format as well as provide a video?

**Comment by vret001** [comment]
Please put all anti cheat related issues in #144
