### ISSUE TITLE
Mosura's Wing Hues

### ISSUE THREAD

**Issue by bonk64** [vret001/KU#169]
**Describe the bug**
Normally, Mosura's wings shift to blue to orange to green, etc.. However they don't seem to do this. They only start to shift during the effects of Saving Grace and after you use a move that would change the wing's hue (Unerring Light, Queen's Call, Queen's Roar.)

**When did you last experience the issue:**
3/4/22, 6:39 PM EST

**To Reproduce**
1. Select and spawn in as Titanus Mosura
2. Idle for a while, and look at her wings
3. Use Saving Grace and notice that her wings now shift correctly

**Expected behavior**
Mosura's wings would fade into different hues while idling.
**Screenshots** (sorry if the images dont work)
The image shows Mosura during Queen's Roar (normally, her wings would be a purple/violet):
![image](https://user-images.githubusercontent.com/100976480/156856607-c1db1b19-79ab-4d11-98bb-9a75c04eb6e4.png)

This image shows how her wings should look like normally (in this case, during Saving Grace):
![image](https://user-images.githubusercontent.com/100976480/156856902-0cd637d1-e006-4148-9506-350df0949abd.png)

Additionally, a video showcasing the bug:
(apologies if the video is low quality) https://youtu.be/W89Sjduj-yw

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 21H2 (for Windows)

**Additional context**
If it's needed for anything my discord tag is bonk#7446.

**Comment by Zeely-Weely** [comment]
This is intentional behavior, this has been changed.
