### ISSUE TITLE
Unclear/Incorrect hitboxes for fliers

### ISSUE THREAD

**Issue by ShikikanV** [vret001/KU#170]
A flier's hitboxes while flying are positioned below the kaiju.

5/3/2022 12:15PM AEDT

1. Play as a flier
2. Fly(pressing shift)
3. Press down on the ground.

There will be an invisible object blocking your flier from touching the ground without jerking somewhere.

Screenshot/Video:
https://streamable.com/nvqc99

Desktop: 
Microsoft Surface Laptop Go

**Comment by DiscoDragons3** [comment]
the only thing I found was on mog

**Comment by vret001** [comment]
@Zeely-Weely you need to update the animations of the really old flying kaijus to not have a y-offset
