### ISSUE TITLE
Shin 4 1.3x is incorrectly listed as having a 1.3x strength buff

### ISSUE THREAD

**Issue by N13F** [vret001/KU#173]
Describe the bug
Shin's description says that he gets 1.3x stronger the fuller his energy bar is, but there's no notable changes in combat.

When did you last experience the issue
March 4th, 2022

1. Select and play as Kamakura-San (Shin 4)
2. Immediately use evolutionary boom 
3. Use an attack at a low energy bar
4. Then compare damage or any change with a full energy bar

**Expected behavior**
Shin would have some type of change or buff the fuller his energy bar gets.

**Screenshots**
![RobloxStudioBeta_etTrACgB4g](https://user-images.githubusercontent.com/100981997/156866141-10c706e0-ac91-4991-bd9b-3d72ce98be37.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 99.0.4844.51

**Additional context**
The description for the 1.3x stronger buff doesn't tell on what exactly is strengthened the fuller Shin's energy bar gets.
I don't know whether it is mentioning that Shin is 1.3x stronger due to building up energy and using an evolutionary boom or if it's a passive ability with Shin's energy bar.

**Comment by vret001** [comment]
@Zeely-Weely Please change shin's description to remove the 1.3x stronger.
