### ISSUE TITLE
MZ Concentrate has no sound

### ISSUE THREAD

**Issue by Dareetos** [vret001/KU#174]
Description
MZ's Concntrate does not have its charge sound (the electric buzzes)

When did you last experience the issue:
12:03 AM PST 3/5/2022

To Reproduce
1. Use MZ's Concentrate

Expected behavior
Normal sounds configured by the devs

Proof
https://streamable.com/02hutu

**Desktop (please complete the following information):**
 - OS: Unable to give
 - Browser: Firefox
 - Version: Unable to give

**Comment by Zeely-Weely** [comment]
This seems to be a Roblox issue, the sound plays as intended on our end.
