### ISSUE TITLE
Femuto's R roar has no sound and slowed animations.

### ISSUE THREAD

**Issue by Dareetos** [vret001/KU#175]
Description
Female Muto's T Roar has no sound and its animations are slower

**When did you last experience the issue:**
3/5/2022

**To Reproduce**
1. Use Femuto's T Roar

**Expected behavior**
A non-glitchy roar

Proof
https://streamable.com/c8gd80

**Desktop (please complete the following information):**
 - OS: Unknown
 - Browser; Firefox
 - Version: Unknown

**Comment by Dareetos** [comment]
Forgot to mention that Roblox volume is maxed out

**Comment by Zeely-Weely** [comment]
We could not replicate this issue on our end, the animations were fine and the sounds were present.
