### ISSUE TITLE
Shop menu broken

### ISSUE THREAD

**Issue by KERMITisNERK** [vret001/KU#176]
[](https://user-images.githubusercontent.com/61644033/156895238-0adc4383-3ea3-4cd7-9bb7-d390298336a8.png) 
The shop menu is broken and nothing pops up even though i have bought nothing. This problem started for me at 1:00 pm est at 3/5/2022.
image

**Comment by KERMITisNERK** [comment]
[](https://user-images.githubusercontent.com/61644033/156895238-0adc4383-3ea3-4cd7-9bb7-d390298336a8.png) 
The shop menu is broken and nothing pops up even though i have bought nothing. This problem started for me at 1:00 pm est at 3/5/2022.
image

**Comment by vret001** [comment]
Hi, please follow the format.
