### ISSUE TITLE
Kaijus Rubberbanding backwards

### ISSUE THREAD

**Issue by PeskyPenny** [vret001/KU#177]
**Describe the bug**
Upon using a dash attack with a kaiju, it'll send you back to your original location and damage you

**When did you last experience the issue:**
March 5th, 2022. 2:10Pm

**To Reproduce**
1. Go to 'Female Muto'
2. Click on 'Plague Escalation'

**Expected behavior**
The kaiju to be sent back to its original spot and take a big chunk of damage

**Additional context**
It happens with Kumonga, Kamacuras, Mechagodzilla 2021, and Female Muto mostly

**Comment by vret001** [comment]
Please put all anti cheat related issues in #144
