### ISSUE TITLE
Infinite Exp/G-Cell from Godzilla 2021 bug.

### ISSUE THREAD

**Issue by JosiahC4x** [vret001/KU#179]
**Describe the bug**
Infinite Exp/G-Cell from Godzilla 2021: When you kill G21, you can notice it has 0 hp but it's still alive somehow. You can get a lot of Exp/G-Cell every time you attack it.
(I'm not sure if there are other kaijus than just G21)

**When did you last experience the issue:**
 March 5, 2022.
 
**Steps to reproduce the behavior**
I'm not sure how did that happened.
Maybe be Godzilla 2021 and die many times?

**Expected behavior**
This G21 should get disappears but it doesn't.

**Video**
(I know it's hard to see. Sorry...)
https://youtu.be/D_TXPNVsnas

**Desktop**
      - Windows 7

**Comment by Zeely-Weely** [comment]
Has been fixed a while ago.
