### ISSUE TITLE
Water and beams issues or kind off a issue

### ISSUE THREAD

**Issue by SkyFox7071** [vret001/KU#181]
Here are 2 bugs that i found im on pc btw (I feel like the water has more zindex then the beam so the beam just takes the transparency of it) (and for the water it just has a whole if we can say it like that in it its all the way at the same place idk if there is other in other places but i found 1)
![RobloxScreenShot20220305_181140218](https://user-images.githubusercontent.com/101024712/156902930-a12ef790-fe71-4b8a-afdd-d07925af6f77.png)
![RobloxScreenShot20220305_181147651](https://user-images.githubusercontent.com/101024712/156902931-dfd3548c-40ac-4849-bdf2-0f4f48cb854c.png)
![image](https://user-images.githubusercontent.com/101024712/156902939-7912e1ea-6380-4964-bdcc-20719c8a5df8.png)
.

**Comment by vret001** [comment]
Unfortunately this is a roblox issue with overlapping transparencies, not much we can do.
