### ISSUE TITLE
Showa MechaGodzilla 2 All out assault skipping beams

### ISSUE THREAD

**Issue by flanjo** [vret001/KU#182]
Sometimes while using All out assault the animation will play out as normal however, the first two beams will skip and no damage will be dealt and only the third beam will be used, meaning only the rockets and a singular beam is used.

It happens on and off, usually from beamdropping but sometimes on ground.

*

**Comment by Zeely-Weely** [comment]
Your chest beam can be disabled temporarily by taking enough damage, in which case it will not be fired during the All-Out Attack.
