### ISSUE TITLE
Some kaijus turning side to side while being beamed

### ISSUE THREAD

**Issue by TophatMilo** [vret001/KU#184]
**Describe the bug**
Turning side to side while being beamed
**When did you last experience the issue:**
A date and time
10:35 AM 6/3/22
**To Reproduce**
Get beamed by any kaiju with a beam
**Expected behavior**
To stay still and not turn side to side
**Screenshots**
Cant attach video 
**Desktop (please complete the following information):**
Windows 10 PC?

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
This is intentional behavior, this is a hit effect.
