### ISSUE TITLE
Godzilla 2014 Running Footstep Sounds and Camera Shake not in Sync

### ISSUE THREAD

**Issue by Prometheus22443** [vret001/KU#185]
**Describe the bug**
Play as Godzilla 2014 and use Sprint and the running footsteps sounds and camera shake are not on sync with the running animation

**When did you last experience the issue:**
9:18 AM  3/6/2022

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Kaijus'
3. Scroll down to 'Godzilla 2014'
4. Play as Godzilla 2014 and use Sprint

**Expected behavior**
Running footstep sounds and camera shake are supposed to be in sync with its running animation.

**Video**
https://streamable.com/yyee6p

**Desktop (please complete the following information):**
 - Browser: Chrome 
 - Version: Windows 10

**Comment by vret001** [comment]
Hi, does this happen on any other kaijus?

**Comment by Prometheus22443** [comment]
> Hi, does this happen on any other kaijus?

No idea I’ll have to check the other kaijus and see if I do find more I’ll put the videos in this post. If not then that might be the only kaiju that is having the problem?

**Comment by Prometheus22443** [comment]
Haven't seen any other kaiju with this Problem only Godzilla 2014 is having this problem

**Comment by Prometheus22443** [comment]
Just found Type-2 Kiryu running footsteps and shake aren't in sync either going to put it here
