### ISSUE TITLE
Random damage still happening

### ISSUE THREAD

**Issue by TophatMilo** [vret001/KU#186]
**Describe the bug**
Random damage
**When did you last experience the issue:**
A date and time
16:24 6/3/22
**To Reproduce**
Random damage, no idea how to make it happen
**Expected behavior**
To keep swimming without taking random damage
**Screenshots**

**Desktop (please complete the following information):**
Windows 10 PC Opera GX

https://user-images.githubusercontent.com/99981747/156932111-2e58cd4c-2072-4d73-9ed5-4df27775645b.mp4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Please put all anti cheat related issues in #144
