### ISSUE TITLE
3 Bugs in 1 | Fly/tp bug | Building hit bug | Swim bug | Monster Zero

### ISSUE THREAD

**Issue by ToxominApe** [vret001/KU#19]
Describe the bug
Bug 1: Flying tp bug when flying you get randomly tped back and take damage. (around 800)
Bug 2: Building hit with second MZ attack sometimes not counting.
Bug 3: Flying into water and the swim animation will trigger when deep in water.

Server Info: Ping: around 165 ms /// Region: West US /// Server age: 0.90 hours

When did you last experience the issue:
2-18-2022 /// 1300 UTC

To Reproduce
Play as MZ
Bug 1: Fly around and there is a random chance u get tped back. I got the bug in low populated servers. (2 to 3 people)
Bug 2: Use the second attack and there is a chance that buildings wont count. (as shown in the video)
Bug 3: Fly into the water and you will see the swim animation will trigger only when monster zero is deep in the water. 
This happens with other kajiu aswell, for example: MG21, G21, ect.

Expected behavior
Bug 1: For the flight to have no chance at getting tped back at all. The flying bug is half fixed by now. The bug has been made less game breaking but still very anoying. 
Bug 2: For the second attack to work normally and destroy buildings with no problem.
Bug 3: The swim animation the activate when mz is around his torso.

Proof:
I dont have screenshots but i have a video that contains all the info you need. It is too large for Github so i posted it to youtube: https://youtu.be/6Nr88htuhqs

Desktop:
OS: Windows 10
Browser: Chrome, (Roblox +)
Version of the game: 5.3.2

**Comment by vret001** [comment]
Thanks for the report,  The first issue you described should be found in #32, the 2nd issue you mentioned should be fixed and the 3rd issue can be found in #35
