### ISSUE TITLE
Anticheat dashes are still occuring, I'm using a kiryu and it's still here.

### ISSUE THREAD

**Issue by Reset355341** [vret001/KU#194]
**Describe the bug**

**When did you last experience the issue:**
A date and time 3/8/22
16:25 PM

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zeely-Weely** [comment]
Duplicate of #144
