### ISSUE TITLE
why is it called comabt log instead of combat log

### ISSUE THREAD

**Issue by DyinL2** [vret001/KU#2]
**Describe the bug**
A clear and concise description of what the bug is. combat log is spelled comabt log

**When did you last experience the issue:**
A date and time 2022/17/2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/99861867/154415258-c97381c0-cda7-4336-91b3-2107d42daec2.png)

please fix

**Comment by vret001** [comment]
This has been fixed in the next update, thank you for the report!
