### ISSUE TITLE
Spawned under the map

### ISSUE THREAD

**Issue by MrCat2099** [vret001/KU#20]
**Describe the bug**
   i spawned underneath tokyo

**When did you last experience the issue:**
 (18/02/2022) idk if you put the month before or after but it's day/month/year for me

**Screenshots**

![RobloxScreenShot20220218_160241154](https://user-images.githubusercontent.com/99979190/154709843-908e87e8-c96f-4e2d-9a70-37a33fc6e4d5.png)

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #34
