### ISSUE TITLE
Charging attacks glitch

### ISSUE THREAD

**Issue by TophatMilo** [vret001/KU#21]
**Describe the bug**
Charging attacks glitch you into the ground and make you take damage.

**When did you last experience the issue:**
A date and time
15:49 19/2/22
**To Reproduce**

Use a charging attack on any kaiju that has one
**Expected behavior**
To charge in a straight line
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows?
 - Browser [e.g. chrome, safari] Opera GX
 - Version [e.g. 22] Windows 10?

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #32
