### ISSUE TITLE
Unable to purchase Shin form 4 (Shin Godzilla)

### ISSUE THREAD

**Issue by FoXyturKeY91** [vret001/KU#213]
**Describe the bug**

Unable to buy Shin form 4 ( Aka Shin Gojira ) 
Straight up, when I try to look for it, doesn’t show up, as if it never existed.

Also, I had him in lvl 34 before he was removed and re-added, incase that matters. 

**When did you last experience the issue:**
A date and time
March 16th, 9:43 pm 
**To Reproduce**
1. Go to 'Chose Kajiu'
2. Click on ( look for shin form 4 )
3. Scroll down to everywhere 
4. See error ( the shin isn’t showing up no matter what )

**Expected behavior**

unable to see the selection for shin form 4

**Screenshots**

( not applicable for me, I’m mobile but not using computer rn )

**Desktop (please complete the following information):**
 - OS: 
 - Browser Microsoft Edge
 - Version Lastest version ( don’t know, but it’s the newer one )

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro max 
 - OS: IOS 5.1.1 ( couldn’t figure what OS meant )
 - Version IOS 15.1.1

**Additional context**

it’s just basically this for me, look for selection of kajiu, not there, reset phone, use computer, try everything to see if it’s a bug in my phone or computer, and surprise it isn’t. After a few days I try again and it isn’t there. I haven’t noticed this before so this could have been a thing for a while.

if unable to understand, my discord is Vernage#9928 and my discord server user is FoXyturKeY91 ( MG21 Enjoyer )

**Comment by Zeely-Weely** [comment]
This is not a bug; Shin Form 4 was renamed, but his name has been updated again to be easier to find.
