### ISSUE TITLE
Zombie gigans infect is bugged 

### ISSUE THREAD

**Issue by TheDarkDoc** [vret001/KU#214]
**Describe the bug*
so I’ve tryed testing to see if I can infect people with zombie gigan but have noticed that the infect dosent seem to be working I’ve tried to infect other Kijus and even when they sit there and want to be infected they almost die and they never get infected. I’ve spoken to one other person who has also noticed this bug and seen a recent YouTube video going over the topic. 

**When did you last experience the issue:**
2022 march 16

**To Reproduce**
1. Go to kiju univers
2. Click on zombie gigan 
3. Test if the infect is working on another kiju

**Expected behavior**
Well I expected the other kijus to be infected even if it was a low chance I’d think after trying on a bunch of different kiju it would have worked at least once. but it hasent 

**Screenshots**
I don’t know what I would screen shot to show this issue 

**Desktop (please complete the following information):**
 - OS: 
 - Browser []
 - Version [

**Smartphone (please complete the following information):**
 - Device: [iphone Xr]
 - OS: [Ios 12.2]
 - Browser [roblox app]
 - Version [version 15.3.1 ]

**Additional context**
I’ve seen YouTube videos of people infecting other people in dec wich was 3 moths ago as of writing this. And it was working just fine then but as of recently it seems to just not work at all. If you could test this yourself and maybe if it is buged fix it.        It’s just not the same being zombie gigan and not terning other people into zombies

**Comment by vret001** [comment]
Infections were disabled. This is intentional behavior.
