### ISSUE TITLE
Unable to menu on xbox

### ISSUE THREAD

**Issue by RiverRex** [vret001/KU#217]
**Describe the bug**
Whenever I try to press the menu button it doesn't work

**When did you last experience the issue:**
Every single time I have logged on for a while now
Unsure as to exactly how long though

**What kaijus does this affect:**
Any kaiju

**To Reproduce**
1. Go to Kaiju Universe on xbox
2. Load in as any kaiju
3. Click on menu

**Expected behavior**
To be sent back to the menu

**Screenshots**

**Device Information**
 - Device: Original Xbox 1
 - OS: [e.g. iOS, Android, Windows, MacOS]

**Console log**
Doesn't exist because roblox on xbox

**Additional context**

**Comment by Coercionist** [comment]
Use the right bumper, I play on xbox too and figured this out recently
