### ISSUE TITLE
Dest glitch

### ISSUE THREAD

**Issue by Coercionist** [vret001/KU#22]
**Describe the bug**
A clear and concise description of what the bug is. Using destoroyah the floral beam it should take 33% of your remaining health however using the floral beam now it takes 33% of your max hp 

**When did you last experience the issue:**
A date and time Friday the 18th of February 2022 at 11:08

**To Reproduce**
1. Go to kaijus
2. Click on dest
3. Scroll down to floral beam 

**Expected behavior**
A clear and concise description of what you expected to happen. I expected it to take 33% of my current hp as it says in the description

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8] 

**Additional context**
Im in xbox so the error may vary

**Comment by vret001** [comment]
This is intentional behavior. This was part of a recent rebalance to Destoroyah,
