### ISSUE TITLE
Kong's healing gives back 3.9k, Kamoebas heal gives back 100 HP, and Behemoth's healing gives no HP

### ISSUE THREAD

**Issue by solgaleo2135** [vret001/KU#221]
**Describe the bug**
Kong's healing makes him basically immortal, while the other kaiju with healing moves get just about no HP from it

**When did you last experience the issue:**
A date and time
18/3/22 11:00 PM EST

1. select Kong, Kamoebas or Behemoth
2. use their respective healing moves when at low HP
3. observe results

**Expected behavior**
when Kong's healing is used, it should return you to full hp, whereas with Kamoebas and Behemoth, they do not heal at all, or barely

Videos
https://user-images.githubusercontent.com/101913364/159104508-d6a01cdb-5358-41ac-9a88-a90a2777b77a.mp4 - Kong healing
https://user-images.githubusercontent.com/101913364/159104519-6f682b95-15e5-4cb0-95eb-8c68ada95722.mp4 - Behemoth healing
https://user-images.githubusercontent.com/101913364/159104529-871ba0be-3c24-4a96-8868-b5cf35a38c94.mp4 - Kamoebas healing

Desktop, WindowsOS, Chrome browser, version 99.0.4844.74

**Comment by vret001** [comment]
Fixed in new servers
