### ISSUE TITLE
Died when spawn in Tokyo

### ISSUE THREAD

**Issue by CleverPlanet** [vret001/KU#222]
**Describe the bug**
When I hit the ground, it set my health to 0 before everything loaded.

**When did you last experience the issue:**
March 18 

**To Reproduce**
Go to Tokyo
1. Go to World

**Smartphone (please complete the following information):**
 - Device: iPad Air 4
 - OS: IOS 15.4
 - Browser safari
 - Version 15.4

**Comment by Zeely-Weely** [comment]
Due to this report's poor formatting and lack of evidence, we are unable to investigate this issue. Please make another report following our formatting guidelines if the issue persists.
