### ISSUE TITLE
Stop Megalon seizures from happening

### ISSUE THREAD

**Issue by toastmoncher** [vret001/KU#228]
I once noticed that the Megalon I was playing as shook uncontrollably, and got anticheat triggered on it, I could not control it from the looks of it, and could not tell if it just affected me or if anybody else could see it.
Megalon shakes uncontrollably, even sometimes flying while shaking, but sooner or later gets back due to anticheat

3/20/2022

- I only saw this bug affect the Megalon I was playing as

I do not know how to recreate the bug, I'm not sure if this bug affects other people and kaiju.

I expect this to be dealt with, as it makes Megalon almost unplayable due to its shaking and flying

**Device Information**
 - Device: Windows 10
 - OS: Windows, Micrososoft
 - 
Proof:
![RobloxScreenShot20220320_153549826](https://user-images.githubusercontent.com/101994680/159182050-2395de95-3a66-48d7-94c4-c87d8258ade7.png)
![RobloxScreenShot20220320_153601126](https://user-images.githubusercontent.com/101994680/159182342-07c2fdfa-f686-4f3d-b891-eb7e0deae9e8.png)
![RobloxScreenShot20220320_153535772](https://user-images.githubusercontent.com/101994680/159182409-2ba63fdf-d3ed-4657-a753-d2630d79200d.png)

**Additional context**

**Comment by Zeely-Weely** [comment]
Hello, how often does this bug occur? Does it still happen?

**Comment by toastmoncher** [comment]
I have not seen it happen in any other Megalons.

But then again, I do not play as Megalon very often, neither does anybody else, from the looks of it. I still can’t tell if it only affects the player, or if everybody else can see it.



-- 
This email has been checked for viruses by AVG.
https://www.avg.com
