### ISSUE TITLE
flying Glitch/Bug

### ISSUE THREAD

**Issue by Kelvpsychiatric** [vret001/KU#23]
whenever i would be playing with MZ, Mosura or other flying Kaiju i would randomly fall and take damage it can be annoying while in combat for example if your fighting a G21 and it uses Hollow Quarry, if it try flying away i would be teleported above the G21 and stop flying for some reason and get hit by alot of the damage (i didn't record that so it happening with Dest is the only video of this i have)

https://user-images.githubusercontent.com/89369302/154725372-fd76bc65-d011-4733-970a-324a32a159da.mp4

**Comment by vret001** [comment]
This should be fixed on most kaijus now, please let us know if it still occurs.
* This still occurs on some dashes, will be fixed.
