### ISSUE TITLE
Multi-beam attacks only have one beam's DPS factored in beam clashes

### ISSUE THREAD

**Issue by Berzerkinblaze** [vret001/KU#231]
**Describe the bug**
Kaiju with multiple beams firing at the same time that are locked in a beam clash will only have a single beam's DPS calculated, meaning even a max damage HKG will lose to a low level Megalon in a beam clash.

**When did you last experience the issue:**
3/21/22, 5:16:41 AM EST

**What kaijus does this affect:**
- Monster Zero
- Showa King Ghidorah
- Heisei King Ghidorah

**To Reproduce**
1. Use a beam from a kaiju that shoots multiple beams at once in a beam clash against a kaiju that has higher beam DPS than one of your beams, but not all of them.

**Expected behavior**
All fired beams' DPS would be factored into the beam clash, allowing the kaiju to win beam clashes where the total DPS exceeds the enemy's beam DPS.

**Videos**
https://streamable.com/viq6ah
https://streamable.com/7ndty3
https://streamable.com/doinnp

**Device Information**
 - Device: PC
 - OS: Windows 10

**Console log**
![image](https://user-images.githubusercontent.com/99952389/159235035-64f7e615-420b-456f-a1cb-da07c045ba45.png)

**Additional context**
None

**Comment by Zeely-Weely** [comment]
Thank you for the report! This is intentional behavior and is not a bug.
