### ISSUE TITLE
G21 action delay

### ISSUE THREAD

**Issue by Monarchoutpost** [vret001/KU#237]
**Describe the bug**
The bug I am reporting is about Godzilla 2021, his roar is being delayed and his mouth isn't opening when roaring.
Roar/actions delayed

**When did you last experience the issue:**
Date and time
March 23, 2022 11:45 AM PST (Philippine standard time)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows, Windows 10 64 Bits]
 - Browser [chrome]
 - Version [e.g. 5.6.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 pro max]
 - OS: [e.g. iOS 14.8.1]
 - Browser [e.g. safari]

**Additional context**

**Comment by Zeely-Weely** [comment]
This report has not followed the correct format and lacks any form of proof or steps to reproduce, and as such, we do not have the sufficient information to investigate this issue. If the issue persists, please make another report with the appropriate format.
