### ISSUE TITLE
Manda's Serpentine Strike causes the kaiju to lose control

### ISSUE THREAD

**Issue by VixenSaid** [vret001/KU#24]
**Describe the bug**
^
•Manda bugs out when using Serpentine Strike. Upon activating the skill - Manda’s movement seems to disconnect from you inputs and starts sliding around especially in water which also makes it drop to the bottom. This bug is similar to the spawn bug where your Kaiju has to snap to control lock after a few seconds to work upon spawning. It prevents from using control lock very well and makes moving disorienting underwater.

**When did you last experience the issue**
^
•Around 11:25 EST, 2/18/22  

**To Reproduce**
^
•Steps to reproduce the behavior:
1. Go to the Kaiju menu.
2. Spawn in as Manda.
3. Click on Serpentine Strike.
4. Jostle your camera around with and without control lock while moving.
5. See the error.

**Expected behavior**
^
•I expected to be able to use Serpentine Strike to range from the water, but when I tried that I dropped to the bottom of the pool and started bugging out instead.

**Evidence**
^
https://user-images.githubusercontent.com/63977689/154726910-8bbf105f-ff03-495d-b3e2-f5a1836eab23.MOV

**Smartphone**
^
 - Device: [iPhoneXS Max]
 - OS: [iOS 15.2.1]
 - Version [5.3.0]

**Additional context**
^
Apologies if I got anything wrong with the format. I don't often report to GitHub

**Comment by VixenSaid** [comment]
I'm not sure if the video works on PC, but I can always privately send it if you want to look at the issue further, Verret.

**Comment by vret001** [comment]
This should be fixed in the latest update. Please let us know if this issue still occurs.
