### ISSUE TITLE
Jet Jaguar Beta swimming underground

### ISSUE THREAD

**Issue by SpooderMan2** [vret001/KU#242]
Describe the bug
The bug is about when Jet Jaguar Beta is swimming towards Birth Island.
A clear description of the bug is.
When you swim to a certain spot at Birth Island, you are able to go under the ground, making it hard for people to find you (if you are being chased).

When did you last experience the issue:
3-23-2022 6:05 pm

What kaijus does this affect:
So far it only happened with JJB.

To Reproduce
1. Go underwater near Birth Island
2. Go to a certain spot at Birth Island (near the waterfall)
3. Swim into the spot without going above water level

Expected behavior
I expected to go onto land.

Screenshots
<img width="539" alt="ku s1" src="https://user-images.githubusercontent.com/102268879/159822757-7e857c78-a0d2-4074-ae0a-daf91ba8658a.png">
<img width="419" alt="ku s2" src="https://user-images.githubusercontent.com/102268879/159822780-2697ce99-f1a2-476c-b75c-440385e697dd.png">
<img width="454" alt="ku s3" src="https://user-images.githubusercontent.com/102268879/159822785-a37bf07a-a514-43a4-9c13-4419e28b6b7d.png">

Device Information
 - Device: PC
 - OS: Windows

Console log
<img width="803" alt="image" src="https://user-images.githubusercontent.com/102268879/159824185-bcef2498-9b8c-4765-af5a-08bcb0e34a14.png">

Additional context
Others have seen me underground whenever it happened.

**Comment by Newnugget1** [comment]
You forgot to add the timezone .-.

**Comment by SpooderMan2** [comment]
Sorry about that. If it would help here I'm in PST. Unless you need me to
make new one p.p
