### ISSUE TITLE
Kumonga Dance move missing audio

### ISSUE THREAD

**Issue by ColWilBald** [vret001/KU#246]
**Describe the bug**

Using Kumonga's dance V move doesn't generate any music.

**When did you last experience the issue:**
A date and time

3/24/22 7:05 PM

**To Reproduce**

Use Kumonga's level 50 V move

**Expected behavior**

Usually, music is emitted while using this move.

**Screenshots**

**Desktop (please complete the following information):**

Windows 11 version 21H2, chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Newnugget1** [comment]
oh sup ColWilBald
