### ISSUE TITLE
Rule 1's incomplete sentence

### ISSUE THREAD

**Issue by ThePterosaur** [vret001/KU#247]
**Describe the bug**
I do not know if this really a bug, but rule 1 does not say where you can find the amount for teaming

**When did you last experience the issue:**
3/25/2022 4:25 AM CST

**To Reproduce**
1. Go to chat
2. Type in /rules
3. Scroll down to read the rules

**Expected behavior**
I expected it to say where to find the amount a kaiju can team with

**Screenshots**
[Roblox 3_25_2022 4_25_36 AM (2)](https://user-images.githubusercontent.com/102193245/160093986-14c3050c-95b2-4cb4-b822-1670824893dd.png)
**Desktop (please complete the following information):**
 - OS: 19043.1586
 - Browser Google chrome
 - Version Windows 10 Pro

**Smartphone (please complete the following information):**
 - Device: Galaxy S10
 - OS: Unable to be found (somehow)
 - Browser Google chrome
 - Version 12

**Additional context**
No additional context

**Comment by Zeely-Weely** [comment]
It in fact does, but Roblox is cutting out the chat on mobile for some reason. Not much we can do about it, sorry, but it's in the kaiju's stats.
