### ISSUE TITLE
Spawning under tokyo & glitched Frostbite rigging

### ISSUE THREAD

**Issue by axobagel** [vret001/KU#25]
**Describe the bug**
When I tried to spawn in Tokyo, I spawned under the map, screenshots below. Also, this may be a seperate bug but I haven't played in a long time, and for some reason my frostbite godzilla was swimming... upside down.

**When did you last experience the issue:**
Friday 18th of February, 22:03 GMT

**To Reproduce**
1. Go to SPAWN
2. Click on TOKYO
Note: This may be a one-time glitch, I don't klnow, when I joined the other day, I spawned just fine, Also, my Frostbite was swimming upside down then too.
**Expected behavior**
I thought (when I clicked TOKYO) that I would spawn in Tokyo.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - Version: MacOS 11.6.
![Screenshot 2022-02-18 at 21 58 39](https://user-images.githubusercontent.com/94447971/154767593-85c4c83c-1703-48d0-85c2-1de17d234757.png)
![Screenshot 2022-02-18 at 21 58 34](https://user-images.githubusercontent.com/94447971/154767933-f32b638f-2a74-4d19-b46c-0a17a5b76756.png)

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #34
