### ISSUE TITLE
Bug Report With Sprinting

### ISSUE THREAD

**Issue by JonnyHB** [vret001/KU#251]
Sprinting Sucks

Happens every time I play the game

Sometimes when you sprint and don't have sprint toggle on you sprinting glitches out.
If you are sprinting then let go of shift and try to press it again quickly, your sprint will not activate.
It is so stupid because it makes pvp with certain Kaiju a pain when you are holding shift down and you aren't sprinting.
To fix it you have to stop moving completely and start sprinting again, or just hope your sprint works again.
It is hard to describe how it happens but it almost feels like there is a timer on the sprint button or something.

**Comment by Zeely-Weely** [comment]
The behavior described is intentional and is not a bug. Moreover, please follow the format for bug reports, as if this WAS a bug, we would not be able to investigate it given the contents of this report.
