### ISSUE TITLE
Monster Zero 'Concentrate' moves your model uncontrollably

### ISSUE THREAD

**Issue by TheHahaMan8** [vret001/KU#253]
**Describe the bug**
Monster Zeros 'Concentrate' Animation moving model through walls

**When did you last experience the issue:**
11:24PM EST, 3/26/22

**To Reproduce**
1. Go to 'Monster Zero'
2. Click on 'Concentrate while on any slightly uneven surface'
3. Begin to slide through walls

**Expected behavior**
Monster Zero should be still while using this ability.

**Screenshots**
For Clip, please DM me on Discord: TheHahaMan_8#8807

**Desktop (please complete the following information):**
 - OS: PC
 - Browser: Chrome
 - Version: Don't Know

**Comment by Zeely-Weely** [comment]
Could you please upload the clip you have to [streamable](https://streamable.com/upload-video) or another service and put the link here? It's really easy and we need everything to be on GitHub to keep things organized.

**Comment by TheHahaMan8** [comment]
Of course, here's the clip:
https://streamable.com/z6nsfh
