### ISSUE TITLE
Shin 4 Tail Bug

### ISSUE THREAD

**Issue by TheEmperorNeo** [vret001/KU#256]
**Describe the bug**
Shin 4 tail beam not moving

**When did you last experience the issue:**
A date and time
8:32 and the date is 3/27/2022

**Expected behavior**
I was trying to do the move with tail beam but the tail isn't moving

**Screenshots**
![RobloxScreenShot20220327_201729918](https://user-images.githubusercontent.com/102483492/160295635-22357408-371c-4a50-94d1-b934058a3d41.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] HP
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] intel core i3 8th gen

**Additional context**
![RobloxScreenShot20220327_201729918](https://user-images.githubusercontent.com/102483492/160295742-cef0a479-97e1-40e1-b43d-11bc5eeaed59.png)

**Comment by Zeely-Weely** [comment]
Hello, could you try replicating this issue and getting a clip of it? Thanks!
