### ISSUE TITLE
The game needs optimization due to poor performance

### ISSUE THREAD

**Issue by Madnesslayer** [vret001/KU#259]
**Describe the bug**
The game needs optimization, although I don't have a good phone or wifi it would be fine

**When did you last experience the issue:**
Since ever

**To Reproduce**
None in particular

**Expected behavior**
Nothing special, the lag but I decided to report it to be able to play better

**Screenshots**
I tried to send one but for some reason I can't

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:ZTE BLADE V
 - OS: Android
 - Browser:chrome
 - Version:8.0.0

**Additional context**

**Comment by Madnesslayer** [comment]
Forget the additional context, there is nothing special with it, there could also be a wrong word or something because I am writing in English through the translator

**Comment by Zeely-Weely** [comment]
We try very hard to optimize the game the best we can, without any specifics of what's causing lag for you, there is nothing we can do to address the issue.
