### ISSUE TITLE
Monster Zero can use tempest and concentrate at the same time

### ISSUE THREAD

**Issue by larity3085** [vret001/KU#26]
Time and date 6:40 am
Bug: mz can use tempest and concentrate at the same time
Steps to reproduce: have atleast 6 charge and use r and v at the same time, it will make inner storm go up and down alot
Proof:

https://user-images.githubusercontent.com/100001316/154771891-b3482b06-0f15-41db-a637-2b00424e3af8.mp4

**Comment by vret001** [comment]
This should be fixed in the latest update. Please let us know if this issue still occurs.
