### ISSUE TITLE
Voodoon teleporting and getting damage

### ISSUE THREAD

**Issue by Voidkx** [vret001/KU#27]
**Describe the bug**
When playing as Voodoon and Juju you experience a bug that make he get damage

**When did you last experience the issue:**
Friday, 18 Feb 2022, 19:07

**To Reproduce**
1. go to the ground without flying
2. use 2 then immediately 1 while pressing w 
3. you will see the voodoon getting teleported and getting damage

**Expected behavior**
I expect the voodoon just attack normally

**Screenshots**
![RobloxScreenShot20220218_191242258](https://user-images.githubusercontent.com/100001927/154773976-b6f7da3b-76c4-4307-98a1-42d7f9b6e4eb.png)
![RobloxScreenShot20220218_191244425](https://user-images.githubusercontent.com/100001927/154773984-cea9cfb3-34e0-48cd-8e9d-f3a9249295eb.png)

**Desktop (please complete the following information):**
 - OS: Acer
 - Browser chrome
 - Version 10.0.19041.1

**Additional context**
This bug happen in all places

**Comment by vret001** [comment]
Part of #32, please followup there.
