### ISSUE TITLE
Monster Zero

### ISSUE THREAD

**Issue by ksnaooo** [vret001/KU#28]
**Describe the bug**
 I don't feel sure this is a bug but, when i used the special ability 'concentration' for too much (like 20 seconds) i was losing so many health (about 800).

**When did you last experience the issue:**
 1:20PM 18/02/22

**To Reproduce**
 1. Get an 'Monster Zero'
2. Click on 'v' ability (concentration)
3. Wait

**Expected behavior**
 I thought when i will use too much the special ability nothing will happen

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Xbox
 - Browser idk
 - Version 5.3.0

**Additional context**
Sometimes it happen when i use it for 3 seconds.
And im sorry about any misspellings

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #32
