### ISSUE TITLE
Biollante regen bug 

### ISSUE THREAD

**Issue by Benjy1902** [vret001/KU#286]
Biollante skill regen does not increase when points are put into it 

11/04/22 22:30pm/UK

Volcanic Biollante
Normal Biollante

1. Go to biollante 
2. Click on skills 
3. Scroll down to regen 
4. Input increased regen and error occurs 

**Expected behavior**
My expectation was that it would increase its regen but nothing changed after i did it 

 Xbox 
![baa676ac-9d18-4bbc-b8b7-4906aeafe6dd](https://user-images.githubusercontent.com/101524424/162836456-5a4687be-c175-4eb0-ad5c-ed9b48658514.png)
![aee7515f-0df3-418c-8916-cae503e79553](https://user-images.githubusercontent.com/101524424/162836465-720bf529-4c63-4030-8107-37e7631d15f5.png)

**Comment by Zeely-Weely** [comment]
The number displayed is rounded, your regen is in fact increasing.
