### ISSUE TITLE
ku gamepass bug

### ISSUE THREAD

**Issue by Devinkanal** [vret001/KU#299]
i got robux today bought the 10k gcells gamepass for 200 robux i got 50k but i buoght the 10k one i speand 2k robux and got 500k gcells and 3 months ago i spend 25k robux for 500k gcells
*
Today cant remember the time

**To Reproduce**
1. Go to shop iname
2. Click on 10k gcellls
4. See that you got 50k gcells and not 10k gcells

**Expected behavior**
i expected to get 10k gcells and not 50k

**Screenshots**
i dont have anny just try yourself

**Desktop (please complete the following information):**
 - OS: dont know what that means
 - Browser edge
 - Version idk

**Additional context**
my discord if you need it: Devin kanal#5630

**Comment by DylantheDilo** [comment]
they have changed the amounts, 1 rbx = 50 gcells instead of before when 1 rbx = 10 gcells, they have said it in the discord but have not updated visuals yet i have already made an report abt it
