### ISSUE TITLE
Flying kaiju teleport bug

### ISSUE THREAD

**Issue by ObungaRequiresToes** [vret001/KU#3]
**Describe the bug**
when using flying kaiju (the only 2 kaiju Ive seen this happen with as of yet is MZ and Showa Mechagodzilla)

**When did you last experience the issue:**
2022/02/17

**To Reproduce**
Play as MZ or Showa Mechagodzilla and start flying around (combat may be what kicks the bug off cause that when it started happening)

**Expected behavior**
the kaiju with teleport randomly and fall out of the sky and start sliding around then fix itself the repeat

**Screenshots**
https://streamable.com/1ld8nu (video proof of bug)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]

**Additional context**

**Comment by vret001** [comment]
We believe we've solved the issue in the next update.
