### ISSUE TITLE
Kumonga dance damages itself

### ISSUE THREAD

**Issue by ObeseWatermelonMonkey** [vret001/KU#30]
**Describe the bug**
Everytime I do the kumonga dance it damages me/and does not work in general.

**When did you last experience the issue:**
10 minutes ago

**To Reproduce**
1. Go to level 50 kumonga
2. Click on spawn
3. Press V

**Expected behavior**
I expected it to actually work
**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Part of #32, please followup there.
