### ISSUE TITLE
(URGENT)Kills are bugged in general

### ISSUE THREAD

**Issue by ShikikanV** [vret001/KU#306]
Kills are:
- Not giving rewards
- Not giving health back 
- Not displayed on chat or upon death of kaiju

Last experienced: 3:02 PM 22/4/2022 AEDT

This affects grinding by a large amount, so technically affecting every kaiju.

1. Kill a kaiju, any kaiju

You should see that:
1. The kill is not displayed
2. The kill does not give rewards
3. The kill does not give you health back(if it has damaged you)

Proof:
https://streamable.com/gar5a8
A max levelled kamata kun, dealing approximately 1200 damage, was killed by me, the Male Muto. The kill did not give rewards, nor was it displayed above the kaiju's corpse or the chat.

Device: Microsoft Surface Laptop Go

This bug affects grinding by a large scale, halving the total income gained from fighting kaiju. This makes it harder to max every kaiju, as kills are bugged in general and do not give exp. Additionally, with the upcoming release of the G19 remodel, which will require a lot of exp, it's important that this bug is fixed ASAP before the release.

**Comment by vret001** [comment]
Issue has been fixed. Thank you for the report!
