### ISSUE TITLE
Sometimes when you are playing as g19, you get teleported backwards randomly. Like back to where you were 10 seconds ago while chasing another kaiju.

### ISSUE THREAD

**Issue by Buffhairman99** [vret001/KU#330]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**What kaijus does this affect:**
- Kaiju 1
- Kaiju 2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information**
 - OS: [e.g. iOS, Android, Windows, MacOS]

**Console log**
Attach an image of the console log here
You can open the console by pressing F9 on PC, or typing /console in the chat on mobile

**Additional context**

**Comment by vret001** [comment]
Hi, this is because your internet had a problem during that time, and the game teleports you back as to make sure you're not cheating. If this happens often please post it in the anticheat thread.
