### ISSUE TITLE
The Script bug

### ISSUE THREAD

**Issue by MeverynewbXD** [vret001/KU#331]
![image](https://user-images.githubusercontent.com/104505443/165518723-1fb720ab-fcf3-4cbc-ad17-75aff341ada4.png)
![image](https://user-images.githubusercontent.com/104505443/165518735-f0a454f7-a7f3-4425-96cf-4ba58f35ca17.png)
I was just gonna buy G21 but i said my G19 is not lvl 30 but my G19 is already lvl 43

**Comment by korelPalmer** [comment]
sigh i feel you bro
