### ISSUE TITLE
Bug  does not let g21 buy

### ISSUE THREAD

**Issue by Drax7239723** [vret001/KU#336]
**Describe the bug**
the bug is that even if you have g14 and g19 at 30 and you have the g cells it won't let you buy g 21

I experienced the bug today while I was finishing uploading to g19 and g14 to buy g21

**Screenshots**
![image](https://user-images.githubusercontent.com/104524958/165593815-78a71083-0595-4ec2-943d-5b4e77527ae4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by korelPalmer** [comment]
same bro i hope they fix it -_-
