### ISSUE TITLE
Bugged Godzilla 2019 Attack Animations When Used Standing

### ISSUE THREAD

**Issue by Prometheus22443** [vret001/KU#363]
**Describe the bug**
Godzilla 2019's attacks look like they are broken or look off after its remodel release. Using the 1st attack Godzilla 2019's arms wouldn't move like he is slashing or biting. The 2nd attack the tail attack starts a bit then skips to the end of the animation not having the tail move full circle in front of him. His 3rd attack when in use Godzilla 2019 would clip into the ground when in use. And for the 5th attack there is not much motion going on when Godzilla 2019 lifts his leg to stomp.

**When did you last experience the issue:**
5/28/2022  10:06 AM

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Kaijus'
3. Scroll down to 'Godzilla 2019' and click Select 
4. Click play and choose any spawn point and start to use any attack while just standing still

**Expected behavior**
All of Godzilla 2019's attack animations when used standing should have more life like movement that it had when it was first released.

**Video**
https://streamable.com/uc44di

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Version: Windows 10

**Comment by Newwindows10** [comment]
you think only hits? there is still one more that is roar r and victory roar
