### ISSUE TITLE
Missions bug

### ISSUE THREAD

**Issue by Tankbtw** [vret001/KU#367]
This bug is in the missions. I finished all my missions and wanted to get the secret prize but it says 2 out of 3 missions complete.But I did all my missions.But I see one mission with its bar at 0.It’s the 15 minutes played in game.I did complete it but it shows that I’m at 0 minutes and can’t get the prize.I don’t wanna lose my streak

This issue started to happend today so 6/16/2022

**To Reproduce**
1. Go to kiju universe 
2. Click on missions 
3. Scroll down 

I expected to get my prize

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [
![image](https://user-images.githubusercontent.com/107644288/174138876-457ba032-6601-401b-8b8b-1065b2ed42aa.jpg)
safari]

**Comment by Tankbtw** [comment]
User:Spongeglocksquarepan

**Comment by vret001** [comment]
Missions reset at 8:00PM EST or 12:00am UTC. They should have reset now, please post here if they have not.

**Comment by Bujuuu54321** [comment]
User: Bujuuu54321
Issue: I've been trying to do a mission called "Visit mothra's egg in Birth Island" and it wouldn't work. I rejoined, tried it 5 times, and it doesn't work.
![RobloxScreenShot20220616_225219739](https://user-images.githubusercontent.com/107660776/174207279-7763ec3a-6bf4-4534-bcad-a23a26eb6ffa.png)
I can't send a video somehow, but you get me.
