### ISSUE TITLE
Golden tree mission wont complete

### ISSUE THREAD

**Issue by iTxrmo** [vret001/KU#372]
![024F2035-ACD5-4094-BBBF-E4CA6AB46AD4](https://user-images.githubusercontent.com/107695291/174311062-dd2cb416-20d4-44a6-a236-a6bf2a53a1c1.png)
**Describe the bug**
the visit golden tree mission wont complete

**When did you last experience the issue:**
last night, 1-2 am and this morning

**To Reproduce**
1. Go to the arctic
2. visit the tree
3. menu
4. mission not completed

**Expected behavior**
i thought the mission would complete, but it didnt

**Screenshots**
![63F4654F-FE5D-447A-BCD3-EA06715C6A48](https://user-images.githubusercontent.com/107695291/174310238-d7299906-7463-42d9-a96b-16d50f0cd03a.png)
![D7204FD1-CF1E-4B00-B14B-4338E8D345C8](https://user-images.githubusercontent.com/107695291/174310249-f30bf4d4-c5e7-4f16-a847-4a0dafe92af5.png)
![Uploading ED58595A-54DD-41C5-AF9D-DD43B753AFDD.png…]()
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: i dont know where this is
 - Browser playing the roblox app
 - Version 15.5

**Additional context**

**Comment by vret001** [comment]
You have to click the tree
