### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by Error4041511** [vret001/KU#376]
Final Mission is missing
![image](https://user-images.githubusercontent.com/107725606/174405093-818c36c2-14dd-44f6-9032-c4e4dd3fa067.png)

**Comment by Gojiro2018** [comment]
I have a similar issue as well, except that the game does not register that I have found the golden tree in the Arctic even though I have been there multiple times as various Kaiju
![Uploading F8F92425-F79F-4798-89AB-70E5693B5FFC.jpeg…]()

**Comment by Bujuuu54321** [comment]
I also have a similar one, i had a mission to visit mothra's egg in birth island. But it  does not register.

**Comment by vret001** [comment]
This was fixed.
