### ISSUE TITLE
Missions stopped working (Day 1, and not showing)

### ISSUE THREAD

**Issue by BlueEnderCookie** [vret001/KU#377]
**Describe the bug**
When I clicked on the missions, I was on day 3. It seemed to have reset and the actual missions themselves didn't appear.

**When did you last experience the issue:**
6/17/22 6:40 PM

**What kaijus does this affect:**
None

**To Reproduce**
1. Go to 'Missions'
2. See error

**Expected behavior**
Supposed to show the actual day that the missions are on and the missions themselves.

**Screenshots**
![Missiona](https://user-images.githubusercontent.com/107734286/174416196-3b6b924a-330b-4db0-a02a-0f688e256caa.PNG)

**Device Information**
 - Device: [PC]
 - OS: [Windows 10]

**Console log**
![console](https://user-images.githubusercontent.com/107734286/174416245-5ab01013-e6f7-496b-a3e7-f83fef58b34d.PNG)

**Comment by vret001** [comment]
This was fixed.
