### ISSUE TITLE
“Find the golden tree” mission bug

### ISSUE THREAD

**Issue by Mr-Megatron** [vret001/KU#378]
**Describe the bug**When spawning in to do daily rewards I head to the artic to get the “find the golden tree mission” and once I did I menued than I went to see that it didn’t work so I tried again and went back as rodan
And still didn’t work (I tried this 3 times with rodan) and than after still not working I went here to report the issue

**When did you last experience the issue:**11:05PM

**To Reproduce**
1. Go to ‘menu’
2. Click on 'spawn at birth '
3. ‘ Go to: artic and find the golden tree than menu

**Expected behavior**
Checking missions spawning in than once you get to the golden tree and respawn it shouldn’t say it counted

**Screenshots**
![3B96D6B3-5860-4F19-BDB0-45A39FDBF2A3](https://user-images.githubusercontent.com/104293188/174422293-f1479381-ddc2-439c-85e5-de496e207d2e.jpeg)

**Smartphone (please complete the following information):**
 - Device: [iPhone6s]
 - OS: [IOS 15.5]
 - Browser [ safari]
 - Version [?]

**Additional context**

**Comment by vret001** [comment]
This was fixed.
