### ISSUE TITLE
"Complete Today's Missions" reward cannot be immediately claimed if "Play for X minutes without leaving" mission was claimed in another server

### ISSUE THREAD

**Issue by MustachioPrime** [vret001/KU#379]
**Describe the bug**
If you have completed the "Play for X minutes without leaving" mission in another server and claim it before reconnecting to another server, your progress will be reset but the mission will still be left as claimed, meaning you must wait the full time before claiming the all mission rewards.

**When did you last experience the issue:**
6/18/2022 1:11 AM

**To Reproduce**
1. Complete time based mission 
2. Leave and rejoin server
3. Click on MISSIONS
4. See that the reward will be claimed but does not count towards your daily mission count

**Expected behavior**
I expected the game to track that I had claimed the time based mission when I would hop to different servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/107742524/174424773-7ddbd142-92e7-4520-badf-15f30cbb4202.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Device: PC

**Additional context**
Reward can be claimed AFTER X time has passed, fixing it would simply be less annoying to complete all missions. 
![image](https://user-images.githubusercontent.com/107742524/174424797-0cba1e49-f87c-4048-a370-e14cf243fd24.png)

**Comment by vret001** [comment]
This was fixed.
