### ISSUE TITLE
Ready Player One Mechagodzilla overcharge glitch

### ISSUE THREAD

**Issue by ColWilBald** [vret001/KU#38]
**Describe the bug**

With overcharge, RPOMG can use its second attack and immediately use another attack. **Both** will have the overcharge effects and buff. This is not the built in double overcharge given between 100% and 0%.

**When did you last experience the issue:**
A date and time

2/19/22 11:20 AM EST

**To Reproduce**

1. Overcharge
2. Use the second attack
3. Immediately use another attack

**Expected behavior**

The attack following attack 2 will not have a damage buff and red effects.

**Screenshots**

Clip is from 9:15 PM yesterday but I found it today too.
[https://streamable.com/o15q8r](url)

**Desktop (please complete the following information):**

Windows 11, Chrome, 21H2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
This has been fixed in the latest update. Thanks for the report
