### ISSUE TITLE
[KU/Mission Bug]

### ISSUE THREAD

**Issue by Cristyan02** [vret001/KU#380]
Its a bug that includes the mission “Visit the mothra egg in birth island”
- Ok so i saw this on my missions tab, i visited the egg on birth island and danced around it, attacked it, all kinds of stuff. I go to the menu and sees that it hasnt been completed yet. So i went it again danced around it, went back to the menu and still not completed. So i went to discord and asked people there, and they told me to click it, And one guy also said his mission (mothra egg mission) vanished. So i opened up KU again checked my missions tab and poof its gone. Thats basically what happened, sorry if its long lol just wanted for u to know the story. But the main issue is:
1. The mission not completing when u visit the egg2. 
2. The mission dissappears

**When did you last experience the issue:**
Roughly around 1:50am, June 18 2022

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error6. 
- I have no idea what to do with this reproduce thingy :)

**Expected behavior**
- Well i expected it to finish instead of it disappearing on me.

**Screenshots**
-  ![6F031451-34C8-44DE-9217-89B797B79C57](https://user-images.githubusercontent.com/107743867/174425472-7fe3f035-24ba-455c-be99-d73ae5b56865.jpeg)
- Ill describe the picture too, the mission literally isnt there. There should be 3 missions listed there but now theres only 2.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: IPAD
 - OS: IPADOS 15.5
 - Browser: Safari
 - Version: What version? idk 22?

**Additional context**
- Thats it.
Anyways hoping u goodluck, hope u can fix this. Rip my day streak tho. Keep improving KU! 
Have a wonderful day

**Comment by vret001** [comment]
This was fixed.
