### ISSUE TITLE
Daily missions

### ISSUE THREAD

**Issue by PumaTheNight** [vret001/KU#381]
Daily missions, today. My missions were to kill three players, visit mothra's egg and break  buildings. When I did the last two, i rejoined to do the first one in a different server. My mothra egg mission wasnt there, everything else was completed. No way of claiming, tried restarting, rejoining, etc. Proof: 
![RobloxScreenShot20220618_101953614](https://user-images.githubusercontent.com/107746479/174427915-81b58485-ec74-43e6-99a9-e9dc21f5797d.png)

**Comment by vret001** [comment]
This was fixed.
