### ISSUE TITLE
Please type a very descriptive issue title

### ISSUE THREAD

**Issue by wheatlyneatly** [vret001/KU#382]
**Describe the bug**
No animations for Wendigo Crawler

**When did you last experience the issue:**
Today.

**What kaijus does this affect:**
- Wendigo Crawler

**To Reproduce**
1. Go to Wendigo Skullcrawler
2. Walk
3. See error

**Expected behavior**
A walk animation to appear.

https://cdn.discordapp.com/attachments/940430258883162152/987733858113945650/Roblox_2022-06-18_10-53-52.mp4

 - Device: [PC]
 - OS: [Windows]

Attach an image of the console log here
You can open the console by pressing F9 on PC, or typing /console in the chat on mobile

**Comment by vret001** [comment]
Did not follow format
