### ISSUE TITLE
MG21 has unlimited regen

### ISSUE THREAD

**Issue by Scrinkytroph** [vret001/KU#386]
**Describe the bug**
Somehow MG21 is unkillable with busted regen
**When did you last experience the issue:**
A date and time 6/19/22   8:40 PM   

**To Reproduce**
Its very awkward and I'm not sure how it works  but this is how it happened. I'm fighting a heisei g as mg21. a mg21 attempts to team with me so I attack him  for a second then go back to the heisei putting me in the usual teaming  2v1 scenario. Then, when the  heisei is killed I chase him and I realize he has unlimited regen absorbing all  my attacks with ease and taking minimal damage from beams and missiles. Some other people started helping me experiment this glitch and  yeah mg21 has so much regen that its unkillable.

**Expected behavior**
I expected it only to effect me but apparently it was server-wide
**Screenshots**
https://youtu.be/7TvpVn-xwlM its a video
**Desktop ( Dell 32'  gaming monitor ):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] 102.0.5005.115

**Smartphone (please complete the following information):**

**Additional context**
I have no damn clue how this happened

**Comment by vret001** [comment]
This has been fixed.
