### ISSUE TITLE
Monster Zero's Inconsistent Grounded Draconian Tempest Hitbox

### ISSUE THREAD

**Issue by Berzerkinblaze** [vret001/KU#39]
**Describe the bug**
Monster Zero's grounded Draconian Tempest appears to have an inconsistent hitbox when used after a while.

**When did you last experience the issue:**
2/19/22, 11:10:38 AM Eastern

**To Reproduce**
Repeatedly use grounded Draconian Tempest until the bug triggers, causing the attack to have a smaller, if not nonexistent hitbox.

**Expected behavior**
The attack would deal damage to all targets in front (and below) in a large range.

**Video**
The bug in question occurs at 0:32 during the second Draconian Tempest on the building against the Monster Zero directly in front of me, and again at 0:53 on the building against the Behemoth below.
https://streamable.com/zxw7qm

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Mozilla Firefox
 - Version: 10

**Smartphone (please complete the following information):**
N/A

**Additional context**
Although both displayed instances occurred with usage on top of a perch, the bug can also occur while on the ground.

**Comment by vret001** [comment]
I believe I've solved this in the next update, thanks for the report.

**Comment by vret001** [comment]
This should be fixed in the latest update. Please let us know if this issue still occurs.
