### ISSUE TITLE
showa mg2 bug

### ISSUE THREAD

**Issue by maybeman0338** [vret001/KU#4]
the bug is that the chest beam does no dmg when used
 
date: 2-18-2022 time: about 10 minutes from the second rebalance update

the steps to reproduce this glitch
1 equip mg2 and use chest beam on any kaiju or building 

the chest beam does no damage 

iam on laptop windows 10

https://user-images.githubusercontent.com/99942723/154621393-3cd89661-6beb-4d80-bf3a-56d9e8d01af7.mp4

**Comment by vret001** [comment]
This has been fixed in the next update. Thank you for the report.
