### ISSUE TITLE
burning godzilla   is only a gray circle with a gray beak and white eyes and no other thing its a weird bug   Feb 19 2022 2:01

### ISSUE THREAD

**Issue by LeFisheAuChocolate** [vret001/KU#40]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Please fill out the format correctly and include video proof, we can not reproduce this issue.
