### ISSUE TITLE
missions bug

### ISSUE THREAD

**Issue by Notenzo** [vret001/KU#403]
ok so missions are bugged i have been completing them repeatedly and it wont budge it says that i have not done the missions even though i did this is very frustrating like dogfight i have killed a flying player in the air but it isn't giving me the rewards for something like buildings it normally works but sometimes it wont register plz fix this because people will get frustrated including me and for people who really g cells i am one of them
![missions](https://user-images.githubusercontent.com/108207423/175799444-ab57f7b0-8601-44e4-bb24-b110b87f754e.JPG)
![missions](https://user-images.githubusercontent.com/108207423/175799456-4f627c15-a011-4361-a9c0-2daf91459598.JPG)

**Comment by Dalvis83** [comment]
The same thing is happening to me, I have done the objective at least 3 times.
