### ISSUE TITLE
kiryu dies before even loading in

### ISSUE THREAD

**Issue by llarmada** [vret001/KU#41]
**Describe the bug**
The first time I load in as kiryu I immediately die before even loading in, it seems to only be the first spawn however. I know its not another player killing me because its during the loading screen while I have spawn invincibility, plus I get 1 shot. it may have something to do with the dashing bug.

**When did you last experience the issue:**
A few minutes ago

**To Reproduce**
1. join a new ku server
2.  spawn as kiryu
3. you instantly die (not entirely sure if its the first spawn, might have to experiment a bit)

**Expected behavior**
kiryu would not die upon spawning in

**Screenshots**
https://i.imgur.com/nlgtNjm.png

https://streamable.com/haffjc

**Comment by vret001** [comment]
Are you able to reliably reproduce this?

**Comment by llarmada** [comment]
> Are you able to reliably reproduce this?
I don't think so, I did a bit more experimenting and it seems to be random chance of it happening, I'll try and do a bit more experimentation tomorrow

**Comment by llarmada** [comment]
Although it seems to only be happening at Prometeia City

**Comment by vret001** [comment]
I couldn't recreate the issue exactly, so most of my fixes are guesses. This *should* be fixed in the next update. Afterwards please let me know if it keeps occuring.

**Comment by llarmada** [comment]
got it, should i tell you here or DM you on discord?

**Comment by vret001** [comment]
This should be fixed in the latest update. Please let us know if this issue still occurs.
