### ISSUE TITLE
the hide gui button doesnt hide player names, making it extremely annoying to get cinematic shots or record cinematic fights

### ISSUE THREAD

**Issue by llarmada** [vret001/KU#42]
**Describe the bug**
HIDE GUI button doesnt disable player names, which makes it nearly impossible to record cinematic fights, not entirely sure if this is a bug or not but I see no reason for it not to.

**When did you last experience the issue:**
ive been experiencing it since the titanus rodan update i believe

**To Reproduce**
1. Load into KU
2. Click "hide gui"
3. stand near a player
4. the name of the player doesnt hide

**Expected behavior**
That the hide gui would hide player names
**Screenshots**
![image](https://user-images.githubusercontent.com/100050546/154823725-9a852747-3890-441f-a4c6-7fa16f921dfc.png)

**Comment by llarmada** [comment]
is this getting fixed?

**Comment by vret001** [comment]
> is this getting fixed?

Yes, we prioritized other bugs first as this is a visual issue versus other bugs that have been affecting player's ability to play at all. We're making our way to this bug now, it should be fixed in the next update.
