### ISSUE TITLE
Destroy buildings mission not counting correctly.

### ISSUE THREAD

**Issue by ThelVadamee8** [vret001/KU#421]
**Describe the bug**
When I have the *destroy x amount of buildings* mission many of the buildings I destroy do not seem to be counting.

**When did you last experience the issue:**
3:16PM on June 30 2022

**What kaijus does this affect:**
All kaijus

**To Reproduce**
Look at how many buildings you have at one time. Destroy a lot of buildings like the entirety of Prometeia city, then look at how much it goes up.

**Expected behavior**
The amount of destroyed buildings should go up by a lot more than it does.

**Screenshots**
I only have a video https://youtu.be/sQbcB4cWt58

**Device Information**
 Xbox series S *I have a mouse plugged in as well as using controller*
 Windows 10

**Comment by vret001** [comment]
Hi, buildings are only counted if they are *fully* destroyed. This means having a building be partially destroyed does not count.

**Comment by Elixir-Golem** [comment]
I am also having this glitch and it make my destroy 800 buildings quest difficult

**Comment by ThelVadamee8** [comment]
Recently I just got Scylla, and I was leveling up from buildings level 1 - 13 and I looked back my missions and it said I had destroyed over 2,400 buildings. I suppose that's another issue with it.
