### ISSUE TITLE
Im on day 11 of the daily quests and i got the quest Aerial Slaughter - Kill 3 flying players

### ISSUE THREAD

**Issue by spreengybont** [vret001/KU#431]
I cannot complete the quest listed in the title 

02/07/2022 23:20

**To Reproduce**
1. Kill 3 flying players
2. Go to the quest
3. Quest isnt done

The quest to be finished

Laptop
Windows

I cant get my random daily now

**Comment by vret001** [comment]
Hi, Did you kill the players while they were flying, or on the ground?
They have to actively be in the air to count them.

**Comment by spreengybont** [comment]
Yes i killed both with beam and with melee in air and it still didnt give me the kills
