### ISSUE TITLE
Mission areal slaughter not working

### ISSUE THREAD

**Issue by brettsmile** [vret001/KU#433]
I have killed atleast 4 flying players as rodan but only 1 of them counted.

The third of July I have got this mission and I still have it and it’s not working.

my username is brettsmile

**Comment by TrollHEhehehaw** [comment]
yep i keep getting this mission and cant do my random prize its so annoying

**Comment by ralthenn** [comment]
I also have this problem. username NathasarNataranju. No progress after fending off an MZ attack while he was flying.
