### ISSUE TITLE
Shins Beam Issue

### ISSUE THREAD

**Issue by ImNotHumanitysALT** [vret001/KU#435]
**Describe the bug**
As A Shin godzilla (Kamakura-san) I found a bug where if i die while beaming it will reset your ability to beam, It only does the thermal flame and it goes into cooldown, no beam at all.
**When did you last experience the issue:**
4/07/2022 9:32

**To Reproduce**
1. Go to any part of the map
2. Try to swim up and use your beam
3. Use your beam, Get killed
4. Bam, now it doesn't work

**Expected behavior**

I expected it to fix itself after I left a joined a different server however it just stayed, never changing.
**Screenshots**
![RobloxScreenShot20220704_095814240](https://user-images.githubusercontent.com/108637438/177061781-27603036-f095-401f-be36-ff65f14e3271.png)

**Desktop (please complete the following information):**
 - Browser Microsoft Edge
 - Version ???

**Additional context**
No other following Problems

**Comment by dannymods** [comment]
I’m having the same issue he’s my favourite kaiju too :/

**Comment by ImNotHumanitysALT** [comment]
Its making me sad cuz i wanna max all the shins :(

**Comment by dannymods** [comment]
Hopefully they fix it I’ve tried everything

**Comment by AxelWasTaken13l** [comment]
Same gurl

**Comment by ImNotHumanitysALT** [comment]
also they needa add a diff discord server for the suggestions / reports cuz what if the banned users catch a bug / hacker that the non-banned dont?
