### ISSUE TITLE
The attack 4 of shin godzilla is not working as it should, it just fires the burst of fire, if after you click again to cast the purple ray it just won't

### ISSUE THREAD

**Issue by Lucas-Vl** [vret001/KU#436]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**What kaijus does this affect:**
- Kaiju 1
- Kaiju 2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information**
 - OS: [e.g. iOS, Android, Windows, MacOS]

**Console log**
Attach an image of the console log here
You can open the console by pressing F9 on PC, or typing /console in the chat on mobile

**Additional context**

**Comment by AxelWasTaken13l** [comment]
Same now my shin's radiation heat ray doesnt work its just thermal flame
