### ISSUE TITLE
Titanus Rodan's Vulcan Burst attack bug

### ISSUE THREAD

**Issue by randomname456** [vret001/KU#438]
**Describe the bug**
Titanus Rodan's Vulcan Burst attack does not sends him flying up

**When did you last experience the issue:**
4/7/2022 8:46 GMT

**To Reproduce**
1. Go to 'Titanus Rodan in Menu'
2. Click on 'Select'
3. Use Vulcan Burst 

**Expected behavior**
Vulcan Burst sends Titanus Rodan flying up properly

**Screenshots**
https://streamable.com/ji40y8

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 105.0

**Additional context**
I hope this will be fix soon because this bug makes Titanus Rodan much easier to hit when it doesn't flying up properly

**Comment by ImNotHumanitysALT** [comment]
Man that sucks, Now he cant be annoying to most flyers
