### ISSUE TITLE
Kamakura-san's Atomic Breath isnt working properly

### ISSUE THREAD

**Issue by madksdakd** [vret001/KU#440]
Kamakura-san's atomic breath isn't working

When:
July 4th 11:15PM

1. Go to Kamakura-san
2. Spawn
3. Click on Shin's 4th attack

Expected behavior
When done using the Thermal Flame attack on Kamakura-san, you should be able to use your atomic breath but the cooldown doesn't let you use the atomic breath attack.

Screenshots:
https://cdn.discordapp.com/attachments/955234428991451136/993717569724887060/robloxapp-20220704-2316247.wmv

**Comment by Sharif2050** [comment]
same

**Comment by AxelWasTaken13l** [comment]
Same

**Comment by AxelWasTaken13l** [comment]
When you already used thermal flame then youre waiting like minutes and then when the cooldown was finish instead of atomic breah/radiation heat ray its bursting the thermal flame again

**Comment by GojiRex** [comment]
Yea, was doing a 1v1 with my friend as Kamakura-San and tried using the beam and didnt work :/
