### ISSUE TITLE
Kamkura-San (Shin Phase 4 )'s Atomic breath doesn't work after Thermal Fire

### ISSUE THREAD

**Issue by VampDusk** [vret001/KU#444]
**Describe the bug**
Kamakura-san's Atomic breath will not activate after the Thermal Fire activation move. Once move 4 is used, it takes quite a while to cooldown. Usually, after using the Thermal Fire move, you can use the Atomic Breath right after but it does not work.

**When did you last experience the issue:**
8:27 PM PST

**To Reproduce**
1. Select Kamakura-san in Kaiju Selection
2. When in-game, select move #4
3. Once "Thermal Fire" occurs, attempt "Atomic Breath"

**Expected behavior**
When in-game with Kamakura-san, move #4, "Thermal Fire/Atomic Breath" consists of a wave of fire breath. Seconds after, once pressed again, The "Atomic Breath" is supposed to come out of the Kaiju's mouth.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 21H1

**Additional context**
I also believe Shin Phase 4 deserves a buff 100%. He's like an XP bag for players to just grind off of. Without the Atomic Breath, he is really just a waste of G-Cells.

**Comment by AxelWasTaken13l** [comment]
Instead its bursting thermal flame again
