### ISSUE TITLE
MZ bug

### ISSUE THREAD

**Issue by ShaggyGod** [vret001/KU#456]
so I discovered this bug and Idk if this is supposed to be a thing ;-;
MZ bug is when he uses an R button 
Thermo pulse is useless against that

lemme explain:
Thermo about to pulse

Mz uses an R key right before thermo nukes

Thermo nukes

Mz doesn't take any damage at all

and the guy that owns that and using this thing says its iframe 

but wth is an iframe, i don't even see this on yt

**Comment by ShaggyGod** [comment]
let me know if this is a bug or suppose to be a thing

**Comment by ImNotHumanitysALT** [comment]
Its supposed to be a thing, its called "I-Frames" another words Invincibility frames where nothing can do damage to mz while its roaring, however its getting reduced to 70% instead of 100
