### ISSUE TITLE
G19 hud glitched

### ISSUE THREAD

**Issue by Mig01010** [vret001/KU#462]
![log](https://user-images.githubusercontent.com/109046261/178166142-e5d8ea44-138a-40e5-9da1-7a74cc014af8.png)
![bug](https://user-images.githubusercontent.com/109046261/178165025-7b7e1a73-c99c-413f-8bee-6cd42f2420c5.png)
**Describe the bug**
I was going to test the G19 nem Primal Charge attack and i noticed my max level Godzilla was with no lvl and stuck at 1450 exp and 1450 hp ( i found out that this is happening with all my kaijus idk if it's only me or to everyone else )

**When did you last experience the issue:**
Day 10 of July of 2022 like 15 minutes ago

**What kaijus does this affect:**
- Godzilla 2019

**To Reproduce**
Spawn as Godzilla 2019

**Expected behavior**
A normal Hud for the 2019

**Comment by Newwindows10** [comment]
Bug my skill v has pic is fw lol
