### ISSUE TITLE
Minilla stats don’t work properly 

### ISSUE THREAD

**Issue by Oedds** [vret001/KU#472]
**Describe the bug**
His speed, health, and attacks aren’t accurate (speed in video)

**When did you last experience the issue:**
Right now.

**What kaiju does this affect:**
- Minilla

**To Reproduce**
1. Go to Minilla'
2. Click on Speed
3. Go into any island
4. Start running, then you’ll see how slow he is compared to how his stats say

**Expected behavior**
Idrk, I expect to be able to run away from kaiju yet it doesn’t work 

**Screenshots** 

https://user-images.githubusercontent.com/100011435/178288507-a81feb9e-c20f-43fd-acc0-8facd37c070b.MOV

**Additional context**
Any kaiju that is the exact same speed goes faster.

**Comment by Newwindows10** [comment]
The animations of minila and jr are different so jr has a faster step-by-step and minila is koq

**Comment by Newwindows10** [comment]
And it's not just minila but all kaiju

**Comment by Oedds** [comment]
doesn’t it?

**Comment by Newwindows10** [comment]
> phải không?

Yes

**Comment by Rqinbxws** [comment]
Having the same issue, I attempt to change the HP and it doesn't change. So its not only his speed, his point's menu is broken
