### ISSUE TITLE
Shin Godzilla form 4 (Kamakura-san) not being able to use Atomic Breath after using Thermal Flame

### ISSUE THREAD

**Issue by supergamers1987** [vret001/KU#473]
**Describe the bug**
After using shin form 4's fire the attack cooldown doesn't come back immediiately essentially making you unable to use his beam
**When did you last experience the issue:**
10:12 AM

**What kaijus does this affect:**
- Kamakura-san (Shin 4)

**To Reproduce**
1. Go to menu
2. Click on Kaijus
3. Scroll down to Kamakura-san (Shin 4)
4. Select Kamakura-san (Shin 4)
5. Click on Play
6. use Thermal Flame/Atomic Breath
7. see error

**Expected behavior**
The attack cooldown should come back right after the Thermal Flame animation is finished.

**Screenshots**
![RobloxScreenShot20220711_105052639](https://user-images.githubusercontent.com/101358830/178292689-a4b3c151-7099-4f48-b896-8a5e32f03ef6.png)
![RobloxScreenShot20220711_105057125](https://user-images.githubusercontent.com/101358830/178292730-202aeb9b-f01f-4701-b300-9c75e104f1f9.png)

**Device Information**
 - Device: Lenovo IdeaPad 3 
 - OS: Windows

**Console log**
![image_2022-07-11_105931938](https://user-images.githubusercontent.com/101358830/178294543-bb1350fc-569c-4463-b9ae-8ada63470050.png)
You can open the console by pressing F9 on PC, or typing /console in the chat on mobile

**Additional context**
I was just playing KU regularly and this happened when I was using Kamakura-san (Shin 4)

**Comment by GLeviii** [comment]
Yes they beed to fix it! I really wanna max shin (lvl 80 right now) but i won't use it until they dont fix this bc Shin 4's not really good if u dont use beam first so it's hard to kill without this. Max speed and max DMG Shin 4 could kill a lvl 80 Ultima before this bug. Hopefully they will fix it as soon as they can.
