### ISSUE TITLE
Strange Flying Glitch

### ISSUE THREAD

**Issue by VixenSaid** [vret001/KU#49]
**Describe the bug**
^
• A flight bug that has been prevalent ever since backwards flying was added to console an mobile. When flying straight up - your Kaiju tends to go back down. This also works in the other direction where going straight down causes your kaiju to go straight back up which makes entering the Tokyo Tunnels to chase someone a hassle. This may be exclusive to mobile and Xbox. 

**When did you last experience the issue**
^
• Around 6:00 P.M.EST, 2/20/22

**To Reproduce**
^
• Steps to reproduce the behavior:

1. Open KU on a mobile device. 
2. Go to the Kaiju menu.
3. Spawn in as any flyer.
4. Go straight up or down for a bit.
5. See the error.

**Expected behavior**
^
• What I expect is being able to go straight up and down without an issue. This doesn't bother me too often until I enter the Tokyo Tunnels since it requires awkward angles.

Evidence
^
https://user-images.githubusercontent.com/63977689/154869143-de07424d-9435-4e21-8e3e-91bd9ceab18b.MOV

Smartphone
^
Device: [iPhoneXS Max]
OS: [iOS 15.2.1]
Version [5.3.0]

Additional context
^
You can of course check on PC if it works on there.

**Comment by VixenSaid** [comment]
The time is 6:00 P.M EST

**Comment by vret001** [comment]
This is an interesting issue. Unfortunately our current usage to get the direction the player is moving is actually a workaround as roblox doesn't supply us any APIs to check directly. I don't know if this issue can be fixed without porting roblox's scripts, something we want to avoid doing as that means we need to maintain and update them.
