### ISSUE TITLE
Final wars stuck sideways

### ISSUE THREAD

**Issue by OneG0** [vret001/KU#5]
**Describe the bug**
Godzilla final wars is stuck sideways 

**When did you last experience the issue:**
2022-02-17

**To Reproduce**
1. Join the game
2. Pick Final war
3. Press play

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 
 - Browser Chrome
 - Version 

**Additional context**
The bug seems very uncommon as I have only found one other person with the bug

**Comment by vret001** [comment]
Could you provide a screenshot/video of this bug? We're unable to recreate it.

**Comment by SuperPNG** [comment]
I have screenshots. This happened to me as well. These all took place around Feb 9th-10th. I'm no developer but I believe it just to be a broken model @vret001 

<img width="1440" alt="Screen Shot 2022-02-09 at 7 20 03 PM" src="https://user-images.githubusercontent.com/100044758/154815806-47898398-ac8a-4404-87a4-f41536b0d0af.png">
<img width="1440" alt="Screen Shot 2022-02-09 at 7 30 22 PM" src="https://user-images.githubusercontent.com/100044758/154815807-3634df2a-cfa9-49fb-9b61-d02688834de9.png">
<img width="1440" alt="Screen Shot 2022-02-09 at 7 31 27 PM" src="https://user-images.githubusercontent.com/100044758/154815811-7c2623f0-17ab-4f1a-ac60-2de67c964516.png">
<img width="1440" alt="Screen Shot 2022-02-09 at 7 41 43 PM" src="https://user-images.githubusercontent.com/100044758/154815812-fdb7b8c0-e932-4533-8c8f-187ca26093c9.png">
<img width="1440" alt="Screen Shot 2022-02-09 at 7 47 07 PM" src="https://user-images.githubusercontent.com/100044758/154815817-ab3d106a-ac8c-4541-954b-d43ed139984a.png">
<img width="1440" alt="Screen Shot 2022-02-10 at 9 59 14 AM" src="https://user-images.githubusercontent.com/100044758/154815818-455f3fd7-2147-4e7e-97fd-dc9249b992b4.png">

**Comment by vret001** [comment]
You have given our rigger nightmares, this should be (hopefully) fixed in the next update.

**Comment by vret001** [comment]
This has been pushed to the update after the current.
