### ISSUE TITLE
Broken kaiju select screen

### ISSUE THREAD

**Issue by Mrlizard1231** [vret001/KU#504]
**Describe the bug**
Makes the kaiju icons too big which doesn't allow me too choose the one I want
**When did you last experience the issue:**
A date and time July 18 6:25pm 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mrlizard1231** [comment]
![20220718_184236](https://user-images.githubusercontent.com/109558317/179629374-69c56d36-6264-4914-aab2-2560cf41caf5.jpg)
Here's the photo for it

**Comment by Bits51verretenjoyer** [comment]
Bro yes literally i have the same problem too![Screenshot_20220719-064751_Roblox.jpg](https://user-images.githubusercontent.com/104266344/179630184-14140ba7-6ec1-4eaa-bff3-1f66e154773a.jpg)

**Comment by FoxoWing** [comment]
I had this same issue. I assume its just a weird update bug, but I hope it gets fixed soon. (The icons being too big is new to me.)
![RobloxScreenShot20220718_181203233](https://user-images.githubusercontent.com/109559787/179632135-4e4dd652-2241-41f9-b6e7-150c82809414.png) You can still play, its just harder to select them.

**Comment by TrollHEhehehaw** [comment]
same its pretty annying i cant choose some kaijus
![image](https://user-images.githubusercontent.com/108618148/179632447-525de9a4-9076-4413-839d-1474f7989867.png)
