### ISSUE TITLE
Kaiju selecting screen bug

### ISSUE THREAD

**Issue by char456780** [vret001/KU#505]
**Describe the bug**
Its a bug where the select tiles are larger and you have to move the mouse/cursor to the left to select the kaiju
**When did you last experience the issue:**
7/18/2022 at 7:36 PM EST

**To Reproduce**
1. Go to Kaiju's
2. See error

**Expected behavior**
to be able to select my kaiju 
**Screenshots**
![RobloxScreenShot20220718_194046811](https://user-images.githubusercontent.com/109560668/179634753-609c78c5-24c9-43b7-9c69-896adb513c53.png)
i selected Female muto and instead of female muto it choosed titanosaurs
**Desktop (please complete the following information):**
 - OS: I don't know how to do it
 - Browser Chrome
 - Version 103
**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bits51verretenjoyer** [comment]
Someone already reported this bug
