### ISSUE TITLE
death issue

### ISSUE THREAD

**Issue by averageKUenjoyer** [vret001/KU#529]
**Describe the bug**
dying and not being returned to the menu

**When did you last experience the issue:**
just today

**To Reproduce**
1. Go to 'anguirus (regular)'
2. get into a fight
3. get killed

**Expected behavior**
i expected to return to the menu

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ASUS gaming laptop
 - Browser [e.g. chrome, safari] microsoft edge
 - Version [e.g. 22] 21H2

**Smartphone**
i don't play mobile

**Additional context**
i honestly don't know how it happened, i was grinding for SP ang and i couldn't return to the menu, menuing doesnt work either

**Comment by TheKaijuFan** [comment]
I rec a clip there's the glitch happen(for more proofs):
https://youtu.be/H1FK7GgZ3hA

**Comment by user92038** [comment]
this happend to me too i own the never respawning one

**Comment by vret001** [comment]
This has been (hopefully) solved in new servers. Thank you for the report.
