### ISSUE TITLE
Beam never ending glitch on all kaiju

### ISSUE THREAD

**Issue by essentery** [vret001/KU#536]
**Describe the bug**
after you beam theres a small chance the beam will not end

**When did you last experience the issue:**
7/24/2022 4:26 AM

**To Reproduce**
1. Go to any kaiju with a beam
2. Use the beam
3. you might need to spam it a lot

**Expected behavior**
for the beam to end after its over

**Video**
https://www.youtube.com/watch?v=IAg2wvbzeWc

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version idk

**Additional context**
its only a visual bug but its still really annoying cause it still tracks your mouse like your beaming

**Comment by trollermazter** [comment]
user:trollermazteryt
bug: beam never ends i try my mecha beam and never ended also my g19
