### ISSUE TITLE
During the titanus rodan update. kaijus such as mz, ultima, g14, heisei, kiryu, etc have broken animations. this has been in the game since the titanus rodan update came out.

### ISSUE THREAD

**Issue by LivingCryopod** [vret001/KU#54]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Please provide reproduction steps and fill out the format correctly, We can't reproduce the issue correctly otherwise.
