### ISSUE TITLE
mg21 roar bug

### ISSUE THREAD

**Issue by maybeman0338** [vret001/KU#56]
mg21 roar has bug

2-22-2022 after the current bug fixes

steps to reproduce are

1st use mg21
2nd use R and T roar

the roars take charge now R roar takes 40 charge and T takes 80 charge and has long cooldown and its shows it has a attack rate

iam on windows 10

https://user-images.githubusercontent.com/99942723/155083683-8195243c-e6ba-4189-abed-a17325db9229.mp4

**Comment by vret001** [comment]
Duplicate of #75
