### ISSUE TITLE
Shin Godzilla Has a Humongous Phantom Hurtbox

### ISSUE THREAD

**Issue by VixenSaid** [vret001/KU#568]
**Describe the bug**
Shin's has a hidden hurtbox that can only be abused by certain attacks such as titano's kick or - much more problematic, ultima's mist. The hurtbox is caused by shin 4's fire attack, and is as large as the attack's range, which is absolutely ludicrous and insanely abusable. This has been a thing for a while now, ever since shin has been out. I thought it would be fixed by now, but I guess not. 

**When did you last experience the issue:**
12:00 P.M EST 7/29/22

**What kaijus does this affect:**
Kamakura-San
Kaiju that can abuse his hurtbox: _*Titanosaur & Ultima*_

**To Reproduce**
1. Spawn in as shin godzilla.
2. Get another player such as an ultima to use mist.
3. Get some distance away from the ultima.
4. Watch as your health goes down from several miles away.

**Expected behavior**
I expected shin to be a little more playable when it was remodeled.

**Evidence**
https://youtu.be/b3v56Ax-0MI

https://youtu.be/ppB6gvNID3M

**Device Information**
 - Device: [e.g. iPhone XS Max]
 - OS: [e.g. iOS 15.5]

**Console log**
![image](https://user-images.githubusercontent.com/63977689/181684347-4691d93c-3525-4b5f-b30d-45deb026799f.png)

**Additional context**
Nothing other than I would like my baby boy shin to be fixed...please.

**Comment by ImNotHumanitysALT** [comment]
Dude what?! THATS SO RIDICULOUS as if the 4 beam glitches arent enough bro
