### ISSUE TITLE
Monster Zero 

### ISSUE THREAD

**Issue by DarrenDC1** [vret001/KU#570]
I recently found out, that the first roar of Monster Zero doesn't work for attacks and beams, when someone beams me, and i use the first roar (R roar) then i still get demage from others, and it wasn't like this before.
And the monster zero got also some problems with attacks, i use one and it appears later, but my wifi is very good and i got no lags ingame, roblox is fine too, so i think it's about monster zero.
To provide demage, you have to click on the R roar (the first one) and you loose no hp.
i didn't know how to screenshot it so i just did a regular screenshot of monster zero.
It got rebalanced some days ago and i think no one is happy with it, i hope you guys fix the bug and make monster zero strong again! 
![Screenshot (57)](https://user-images.githubusercontent.com/110228085/181727524-4614f818-9a88-495b-8070-0dc1d0502c72.png)

**Comment by DarrenDC1** [comment]
i hope this gets fixed and monster zero will be a strong kaiju again, and i hope the shift button will be better because it's not working sometimes and i hate waiting for it to load.

**Comment by Prometheus22443** [comment]
They changed the I frames to reduced damage and flying as a bit of a cooldown u can also go to settings to put toggle sprint/fly where u only need to press shift once to run/walk/fly
