### ISSUE TITLE
Ctrl lock doesn't fully stick on the Kaiju

### ISSUE THREAD

**Issue by Jelliotts** [vret001/KU#59]
**Describe the bug**
When using Ctrl lock on any kaiju it doesn't fully stick on the kaiju you can see as you are running swimming or flying that your kaiju bounces up and down without your camera following it. this also happens with attacks with, (you can see this best on Dest using the Tail whip or Skull Crawler using its Predator's Maul attack

**When did you last experience the issue:**
Any time after Titanus Rodan was released

**To Reproduce**
1. Go to the Kaiju select Screen
2. Click on any kaiju
3. press the ctrl lock button

**Expected behavior**
I expect the camera to follow the kaiju like it did before instead of being glued onto the same spot with no movement when attacking or moving. this bug makes it really hard to fight properly because it doesn't give the player a good visual.

**Screenshots/Videos**

https://user-images.githubusercontent.com/100108958/155184059-d94da820-9cd9-47ac-8075-7f32b07840f1.mp4

https://user-images.githubusercontent.com/100108958/155183785-eb4906dc-74ea-42d9-b97f-bcbe33fe5b4c.mp4

![Roblox 2_22_2022 11_36_25 AM](https://user-images.githubusercontent.com/100108958/155187293-536a1a4e-2244-4213-9180-40acc9321a01.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome,

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Hi, we're unable to reproduce this bug, what device are you using? Are you doing anything of note?

**Comment by vret001** [comment]
This was fixed
