### ISSUE TITLE
Loosing Health and Teleporting as Monster Zero when Doing Concentrate

### ISSUE THREAD

**Issue by GokuTofu** [vret001/KU#6]
When playing as monster zero If you use Concentrate you will loose hp and teleport

Steps to reproduce: Spawn in as monster zero, Press V (Concentrate), Wait 2-9 seconds, The glitch will happen

Date and time: 2/18/2022 12:01 AM

https://user-images.githubusercontent.com/99943442/154621730-3cc35b06-8b10-4878-9f07-573536d2831f.mp4

**Comment by vret001** [comment]
This has been fixed in the next update.
