### ISSUE TITLE
Kiryu malfunction 

### ISSUE THREAD

**Issue by Ticotheoriginal** [vret001/KU#61]
Sometimes when Type 2 Kiryu uses mobilization Barrage you take damage and teleport back to where you used the move

2/22/22 at 1:14 est
Click on Mobilization Barrage 
There is a chance it will work normally 
But mostly the bug happens

You should not just teleport back to where you started the attack and you should not take damage
 
 - Device: [e.g. iPhone6s]

**Comment by Zeely-Weely** [comment]
Duplicate of #144
