### ISSUE TITLE
Bought the Frostbite Godzilla game pass from the original game and did not transfer over

### ISSUE THREAD

**Issue by Bruhster09** [vret001/KU#614]
I Bought the Frostbite Godzilla game pass from the original game and did not transfer over, although I still have access to the Frostbite Godzilla, it says I do not own the game pass and because of this, it does not allow me to play as the new Behemoth character. If there is an easy solution so no one else will have this issue, that would be great.

Username: Bruhster09

**Comment by vret001** [comment]
Hello,
The frostbite gamepass from Kaiju Online was discontinued, as such Frost Behemoth is exclusive to the Kaiju Universe gamepass.
Apologies for the confusion.
