### ISSUE TITLE
I have the frostbite godzilla gamepass but I have it since the old kaiju universe and now it says I don't have it and now that frostbite behemoth has been released I don't have it can you help me with this too? player username:kauan05mi and sorry and i'm sorry if i miss something i just created an account to report this thanks for the contributionI ryanlucass#5699in case you need the evidence

### ISSUE THREAD

**Issue by kauan05mi5** [vret001/KU#615]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kauan05mi5** [comment]
I have the frostbite godzilla gamepass but I have it since the old kaiju universe and now it says I don't have it and now that frostbite behemoth has been released I don't have it can you help me with this too? player username:kauan05mi and sorry and i'm sorry if i miss something i just created an account to report this thanks for the contribution

**Comment by vret001** [comment]
Hello,
The frostbite gamepass from Kaiju Online was discontinued, as such Frost Behemoth is exclusive to the Kaiju Universe gamepass.
Apologies for the confusion.

**Comment by kauan05mi5** [comment]
so but my frostbite godzilla gamepass is not from kaiju online but it's another kaiju universe like there were 2 just wanted to clarify
