### ISSUE TITLE
I have the frostbite godzilla gamepass but since I bought it since Kaiju Online can you please help me? my username is epicsammy1997 thanks for reading this

### ISSUE THREAD

**Issue by epiccccccsammy1997** [vret001/KU#618]
**Describe the bug**

**When did you last experience the issue:**
A date and time

**What kaijus does this affect:**
- Kaiju 1
- Kaiju 2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information**
 - OS: [e.g. iOS, Android, Windows, MacOS]

**Console log**
Attach an image of the console log here
You can open the console by pressing F9 on PC, or typing /console in the chat on mobile

**Additional context**

**Comment by vret001** [comment]
Hello,
The frostbite gamepass from Kaiju Online was discontinued, as such Frost Behemoth is exclusive to the Kaiju Universe gamepass.
Apologies for the confusion.
