### ISSUE TITLE
Health Regen Abilities Broken

### ISSUE THREAD

**Issue by Jelliotts** [vret001/KU#62]
**Describe the bug**
Health regeneration abilities are bugged and don't continue healing after you get hit for some time. what happens now is that while using a regen ability if you get hit it will pause then continue soon after (like normal regen time) the Health getting regenerated is the same but pauses so you have to wait until you start normally regening for the actual affect to kick in

**When did you last experience the issue:**
Right after Framework update came out and still going.

**To Reproduce**
1. Play as any kaiju with Health Regen abilities
2. Get attacked
3. use the Abilities
4. Get hit once more
5. see error

**Expected behavior**
I expect for Health Regen Abilities to continue their effect even after getting hurt instead of needing to wait a good 5-7 seconds in order for them to actually work.

**Screenshots**

https://user-images.githubusercontent.com/100108958/155200158-9a6a6e47-2bf7-4f8b-85f5-7ac9c0040dc4.mp4

**Desktop (please complete the following information):**
 - Windows 10 Pc
 - Browser Chrome
 - Version not sure

**Smartphone (please complete the following information):**

**Additional context**
None

**Comment by Zeely-Weely** [comment]
Thank you for your report! This issue has already been fixed.
