### ISSUE TITLE
slowing down while swimminh

### ISSUE THREAD

**Issue by Kaijusaurs** [vret001/KU#63]
**Describe the bug**
I began swimming as Jet Jaguar Beta but then I suddently start swimming really slowly even as if I was low on health which I wasn't.

**When did you last experience the issue:**
Just 5-10 minutes ago

**Expected behavior**
Slowing down while swimming.

**Comment by vret001** [comment]
Please follow the format more closely and provide reproduction steps. We are unable to reproduce or understand the issue.
