### ISSUE TITLE
Jet Jaguar beta

### ISSUE THREAD

**Issue by TheGamingRhino** [vret001/KU#64]
**Describe the bug**
When you use the dash ability it clips through the ground it doesn't walk straight on the ground and this make it to were I get stuck under people and die because of it

**When did you last experience the issues
2/22/22 at 3:01 pm est time zoner

**To Reproduce**

**Expected behavior**
For it not to clip through the ground and and stay on the island and not go under it

**Comment by vret001** [comment]
Duplicate of #33
