### ISSUE TITLE
I can't buy Type-2 Kiryu

### ISSUE THREAD

**Issue by Aetlaz** [vret001/KU#668]
**Describe the bug**
I can't buy Type-2 Kiryu

**When did you last experience the issue:**
Every time after Millennium Rework update

**To Reproduce**
1. Go to Kaijus (shop)
2. Click on Type-2 Kiryu
3. Can't buy kaiju because ''Millenium Gojira'' is not level 30. (My Millennium is level 30.)

**Expected behavior**
I expected to be able to buy Type-2 Kiryu

**Screenshots**
![image](https://user-images.githubusercontent.com/114311593/192115451-cf74063e-d2e8-41a9-9811-431e6e5e9326.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: 104

**Comment by Kingo253** [comment]
they added an extra n to the kaiju but the requirment has 1 n
so it thinks the millenium isn't millenium

**Comment by Kingo253** [comment]
they have to fix the name
