### ISSUE TITLE
Mechagodzilla's 2021 roar bug

### ISSUE THREAD

**Issue by AMBRANBR3** [vret001/KU#67]
Mecha godzilla's 2021 roar apparently consumes charge and has a giant cooldown

Date : 02/22/2022 or 22/02/2022 18:17 (ETC)

1. spawn with mechagodzila 2021 and roar

Expected behavior : just roar like it should do

video : 

https://user-images.githubusercontent.com/100240235/155222806-9cff1c18-54eb-4870-bae7-16a5a3f2ae65.mp4

Desktop :
 - OS: Windowns 10 Pro
 - Browser : Google Chrome
 - Version : 20H2

**Comment by vret001** [comment]
Duplicate of #75
