### ISSUE TITLE
I cannot get type 2.

### ISSUE THREAD

**Issue by UmbraDaShark** [vret001/KU#671]
When playing KU I managed to my gorija and 2000 Godzilla to the required levels to get type 2. When I tried to buy type 2 it said I had no level 30 2000 Godzilla. But I have a level 42 one which means it’s broken.
Steps to reproduce the behaviour:
1. Go to menu
2. Click on type 2
3. Try to buy it

**Comment by supremeshiva99** [comment]
Same ;/
