### ISSUE TITLE
Can't get Kiryu

### ISSUE THREAD

**Issue by CookieX34** [vret001/KU#684]
I can't get Kiryu for some reason even though i have a level 50 millennium Godzilla, it shows that i didn't complete the level 30 millennium Godzilla part. Can you fix this because i have been grinding for over 3 days and i really want kiryu

Proof:
![Screenshot (3)](https://user-images.githubusercontent.com/114637426/192935690-ae54b9b1-6731-4473-8147-01740d90612a.png)
![Screenshot (4)](https://user-images.githubusercontent.com/114637426/192935699-a89db4ca-d103-4311-a14b-9ed1cf57c120.png)

**Comment by Pickle-98** [comment]
I am also having the problem of not being able to buy type-2 kiryu despite having level 31 millennium gojira. I've been grinding for a long time, just to not be able to buy it.
![kiryu bug](https://user-images.githubusercontent.com/114696552/193125992-e2b45a05-2b11-420e-b4f3-4bc510c40a38.png)
