### ISSUE TITLE
Mecha godzilla 2021 roar bug

### ISSUE THREAD

**Issue by LMarkPlayz** [vret001/KU#69]
**Describe the bug**
when you use both r and t roar the cooldown is way too long and takes all of your charge when use both the roar of mg21

**When did you last experience the issue:**
feb 22 2022

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Duplicate of #75
