### ISSUE TITLE
Rpo Mecha godzilla roars

### ISSUE THREAD

**Issue by LMarkPlayz** [vret001/KU#71]
**Describe the bug**
its another roar bug with rpo mecha godzilla it takes so long for the cooldown both r and t roar cooldown for rpo too long

**When did you last experience the issue:**
i forgot since i don't really use rpo

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
Duplicate of #75
