### ISSUE TITLE
Private Server problem

### ISSUE THREAD

**Issue by randomname456** [vret001/KU#716]
Lose Robux due to Private Server renew

I lose 10 Robux each time my Private Server renew itself
**When did you last experience the issue:**
11/12/22
3:05 PM GMT

**To Reproduce**
Just wait until you suddenly lost 10 Robux and check your Purchased

**Expected behavior**
I don't lost my Robux

**Screenshots**
![robux problem](https://user-images.githubusercontent.com/108640663/201469558-05489b65-c93a-43f0-ac64-2ed891ae2125.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 10

**Additional context**
I don't know if this is a bug but I hope you guys will fix this, please this is important

**Comment by SlayerOfTears** [comment]
Yeah, that's normal. VIP Servers are a monthly subscription, unless you manually cancel them.

![image](https://user-images.githubusercontent.com/116566463/201500976-d5d95d81-fbea-4cea-95ec-5878bae7145e.png)


![image](https://user-images.githubusercontent.com/116566463/201500958-d38c8db1-4e97-4a76-b2c7-7307eb974fd0.png)

**Comment by randomname456** [comment]
oh ok
