### ISSUE TITLE
Titanus Mosura's Striking Pivot Alternate Animation is Bugged

### ISSUE THREAD

**Issue by Kodukushi** [vret001/KU#80]
**Describe the bug**
When on the ground "Striking Pivot" has an alternate attack animation; however, as of now it is bugged and it doesn't make Mosura dash forward.

**When did you last experience the issue:**
02/23/2022 | 4:14 PM  [ UTC+8 ] 

**To Reproduce**
1. Go on the ground
2. Use Mosura's Striking Pivot attack
3. Observe the attack animation

**Expected behavior**
Her alternate attack animation used to consist of a short dash, and a slice.

**Screenshots**

https://user-images.githubusercontent.com/100226492/155369057-7b86b84c-5d46-4956-b23a-9a3eccf8b74a.mp4

( I would like to apologize for the quality, my roblox had been minimized during the time of recording. )

**Desktop (please complete the following information):**
 - Windows 11 | HP Laptop

**Comment by vret001** [comment]
Hi, this should now be fixed. Please let us know and reopen the issue if it is not.
