### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by ArtFi5** [vret001/KU#81]
Mobile Issues
——————————————————
- Showa Gigan : Recently 2/23/22 on mobile you cannot move while attacking with “M1/attack One” “M2/attack two” which is really a pain

so please fix it if possible for mobile
- Art5..

**Comment by vret001** [comment]
We are unable to reproduce this issue. Please follow the format so we can get the full amount of information we need. Attaching a video would additionally help.
