### ISSUE TITLE
Rodan Control Lock Not Centered

### ISSUE THREAD

**Issue by KingKong19100** [vret001/KU#83]
**Describe the bug**
Whenever I hit CTRL to activate the Con Lock, especially for Rodan, it is never centered but is instead out more to the right. This results in the character not working properly, as things like his Ragnarok attack fire more to the right since that is where the cursor is.

**When did you last experience the issue:**
2/23/22

**To Reproduce**
1. Select Rodan and enter new game.
2. Click "Ctrl" or "Con Lock"
3. See error.

**Expected behavior**
Before the new update, the Ctrl Lock was centered. It is now not centered.

**Screenshots**
![RobloxScreenShot20220223_180453273](https://user-images.githubusercontent.com/75760738/155443454-cb311536-8636-407c-8d21-0eac3fc05e97.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 98.0.4758.102

**Comment by vret001** [comment]
Hi, we intentionally moved the control lock. This isn't a bug.

**Comment by KingKong19100** [comment]
> Hi, we intentionally moved the control lock. This isn't a bug.
Oh, is there a way to have it shift back to how it was beforehand? Would you be able to add that function? I've noticed it is much harder using Rodan like this.
