### ISSUE TITLE
Not working on xbox

### ISSUE THREAD

**Issue by Ilikemen12345** [vret001/KU#84]
Xbox is literally unplayable, it is only for keyboard and mouse which I have when I die it doesn’t load in at all it stays at 410 loading stat.

**Comment by Ilikemen12345** [comment]
![image](https://user-images.githubusercontent.com/100329578/155448345-38f289f1-d4f0-4a95-a32e-920b0ebe9442.jpg)

**Comment by vret001** [comment]
Hi, is this issue still happening?

**Comment by vret001** [comment]
Issue is fixed
