### ISSUE TITLE
World height border is bypassable

### ISSUE THREAD

**Issue by Hypothermicbirb** [vret001/KU#86]
The height limit for the map can be bypassed with flying kaiju with moves that can automatically move the player.

The issue can be experienced at anytime if the user accidently or purposefully does it.

To reproduce the bug all you need is a kaiju that has a attack that automatically moves the player at the direction they last faced, then use the move while looking up to go pass border.

When I first discovered this I did not think I would go above the border until I looked back and saw the another flying kaiju cannot reach me without a ranged attacked.

https://user-images.githubusercontent.com/100330152/155450348-1fb1930c-f4ba-4c7a-bb7a-c5d690e3616f.mp4

Video is attached

Desktop - Windows with the latest version of chrome.

Additional context: If the user is above the height border and moves normally they will be pushed back down below the border.

**Comment by vret001** [comment]
The anticheat will now punish anyone over the world border.
