### ISSUE TITLE
are u ever gonna fix the flying bug?

### ISSUE THREAD

**Issue by fatalisjudgement** [vret001/KU#9]
literally flying makes u bug and take damage, can u fix this its been a long time since this has been happening and its hard to enjoy kaijus such as des and mz[.
![image_2022-02-18_142357](https://user-images.githubusercontent.com/99947553/154629294-0357f02d-f594-4bc9-983a-7871d0a6657b.png)

**Comment by vret001** [comment]
Thanks for the report, this has been merged into #32
