### ISSUE TITLE
There is a red stuff that damage kaiju

### ISSUE THREAD

**Issue by CHAOSGAMING2021** [vret001/KU#90]
![Uploading 8C94609A-863C-49AF-BC8B-A18D724BFD30.png…]()

**Comment by CHAOSGAMING2021** [comment]
![Uploading B9B3E941-B86A-46D0-A4FF-B2D7D94D92DE.png…]()

**Comment by Diamondxdragon** [comment]
The red stuff is either the mist from ultima or the damage filter which you can turn off
