### ISSUE TITLE
The false max dmg of the Ruinous Thunder. (Monster Zero 5th attack)

### ISSUE THREAD

**Issue by YellowMonsterkilla10** [vret001/KU#96]
**Describe the bug**
It seems max dmg Ruinous Thunder is a bit bugged In term of dmg not doing 3200 dmg, instead it does 2665 dmg when facetanking MZ .

**When did you last experience the issue:**
Febuary 24th 2022 11:40 UTC

**To Reproduce**
1. Select Monster Zero and choose the spawn place.
2.  Charge Inner storm.
3. Find a player that is willing cooperate to get hit by full force of Ruinous Thunder.

**Expected behavior**
Expected to do 3200 dmg as stated in MZ attack's stats list

**Screenshots** (Note im not sure if that MZ did Full dmg on the bridge since the bridge got destroyed at 5th per hit of 533 dmg)

https://user-images.githubusercontent.com/99962562/155580171-5eb8d1c2-1c57-4dbe-aca4-8f44d97c22d8.mp4

https://user-images.githubusercontent.com/99962562/155580217-67d0b831-cbba-44f7-a34d-1f4788fed0fc.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 11

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by vret001** [comment]
Hi, this is actually not a bug. Ruinous Thunder works like a pulse, meaning it expands over time. The further you are aware, the less time you're taking damage. 

You can see in your video where the trees are taking damage but the other player is just far enough away to not yet take damage.
![image](https://user-images.githubusercontent.com/55320358/156471402-f5f330bb-e36b-49eb-b53e-24dd79b555a1.png)

If you were standing on top of the other kaiju then you would see the full damage.

**Comment by YellowMonsterkilla10** [comment]
> Hi, this is actually not a bug. Ruinous Thunder works like a pulse, meaning it expands over time. The further you are aware, the less time you're taking damage.
> 
> You can see in your video where the trees are taking damage but the other player is just far enough away to not yet take damage. ![image](https://user-images.githubusercontent.com/55320358/156471402-f5f330bb-e36b-49eb-b53e-24dd79b555a1.png)
> 
> If you were standing on top of the other kaiju then you would see the full damage.

ahh i see thx for anwsering me so if i gotta do full dmg i just have to sit on top kaiju in order to do full dmg of ruinous thunder like this one i tried? 

https://user-images.githubusercontent.com/99962562/156475629-f55cab82-1cef-47a2-9e15-3bb6d354b083.mp4
