### ISSUE TITLE
Kamadolph’s dance not working

### ISSUE THREAD

**Issue by Mrsicardo** [vret001/KU#98]
It doesn't allow me to use the Kamadolph's dance correctly more than once.

My last experience was today

1. Enter to KU
2. Choose kamadolph 
3. Play R option
4. Try again
5. Kamata didn’t dance :(

Kamadolph didn’t dance again if you play R option

Playing on iPad

 - Device: [iPad6t]
 - OS: [iPadOS 15.1]
 - Version [15.1]

From Mexico <3

**Comment by vret001** [comment]
Hi, could you provide a video of this?

**Comment by vret001** [comment]
We can't reproduce this issue. No one else has made a report, as such we will be closing this.
