### ISSUE TITLE
zombie gigan infection not working

### ISSUE THREAD

**Issue by hwdqhdwahd** [vret001/KU#99]
**Describe the bug**
well theres not much explanation here the infection isnt working at all

**When did you last experience the issue:**
now and started a few months ago

**To Reproduce**

**Expected behavior**
i expected it to work

**Screenshots**
doesnt need

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser safari
 - Version [e.g. 22]dont know

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment]
This is intentional behavior. The infection was deliberately removed. It will return in the future.
